### ISSUE TITLE
 单列样式百度搜索输入框变短了

### ISSUE THREAD

**Issue by sunnycoffee** [langren1353/GM_script#10]
单列样式，百度输入框变短了。文本太长的时候和 ”语言输入“、”上传图片“按钮重叠（原始模式就就没问题）。
![image](https://user-images.githubusercontent.com/3132535/55378440-8b54a800-554b-11e9-8e8a-abfb98cde4bc.png)

**Comment by langren1353** [comment]
谢谢反馈，我抽时间去看看去，尽快搞出来
