### ISSUE TITLE
最好点击搜索结果所在的框就能跳转

### ISSUE THREAD

**Issue by Krysl** [langren1353/GM_script#108]
每次都得移动到标题上点击才能跳转，有些麻烦（都会耽误零点几秒）。
最好鼠标移进框里面直接就能点。（可能需要排除框内已有的一些超链接，在不是那些链接的位置上都能点击跳转）
希望在自定义菜单里能加个选项，能开启以上功能。

**Comment by langren1353** [comment]
该功能比较蛋疼，暂时不考虑增加该功能
