### ISSUE TITLE
希望域名拦截可以批量添加甚至像广告过滤那样可以订阅

### ISSUE THREAD

**Issue by spphinslove** [langren1353/GM_script#111]
现在谷歌中文搜索的垃圾SEO太多了，点进去全部都是广告，百度也不少。
https://github.com/cobaltdisco/Google-Chinese-Results-Blocklist 这个里面就有很多垃圾域名，希望作者可以重视一下

**Comment by langren1353** [comment]
考虑到某些原因，默认不好加进去
