### ISSUE TITLE
百度搜索UI变化，自定义按钮错位bug

### ISSUE THREAD

**Issue by abc1044** [langren1353/GM_script#112]
近期百度搜索UI发生变化，脚本的自定义按钮会有错位的bug，望修复。

错位bug：
![image](https://user-images.githubusercontent.com/18114052/85946355-72b58680-b976-11ea-879c-c2933d6f339c.png)

设置情况：
![image](https://user-images.githubusercontent.com/18114052/85946339-63ced400-b976-11ea-8f42-f51002282b40.png)

**Comment by talking-toaster** [comment]
新版本 v23.33 已修复
