### ISSUE TITLE
百度自动翻页失效

### ISSUE THREAD

**Issue by shishirong** [langren1353/GM_script#115]
chrome 83.0.4103.116

**Comment by yuannancheng** [comment]
我也自动翻页失效，似乎是百度改版了。之前的百度搜索结果的搜索框是没有圆角的，可以自动翻页。但现在搜出来是带圆角的搜索框，就不能自动翻页了。

**Comment by Iseulf** [comment]
自动翻页失败了，用的Firefox，Chrome可以但Firefox不可以

**Comment by yuannancheng** [comment]
我用的是chromium ，不能自动翻页，chrome还没试过。

**Comment by PPZPPZ** [comment]
edge的自动翻页也失效了

**Comment by Yudezhi** [comment]
Chrome  也失效，期待更新

**Comment by grdaimap** [comment]
+1
