### ISSUE TITLE
关于Edge百度页面显示问题

### ISSUE THREAD

**Issue by LorenzoXue** [langren1353/GM_script#116]
macOS Catalina 10.15.5
浏览器拖窄的时候再拖回全屏，样式不会适应宽度
command+Q退出后再进入问题依然存在
<img width="1746" alt="WX20200629-165751@2x" src="https://user-images.githubusercontent.com/53855044/85994394-52470400-ba2a-11ea-9e30-efa3bb754029.png">

**Comment by Emperorxyz** [comment]
只有单列居中对齐是正常的，其他的都有问题

**Comment by yangyongkangse** [comment]
同问题,在chrome使用正常但是切换会edge是不正常了,双列显示极窄.

**Comment by Emperorxyz** [comment]
> 同问题,在chrome使用正常但是切换会edge是不正常了,双列显示极窄.

官方回复时是：
百度改版导致插件样式样式不正常，目前AC大佬在加紧修复中，请耐心等待！

**Comment by Oz-Starlit** [comment]
同样的问题，稍微看了一下，可以勾选“附加10-自定义样式”，然后在里面写上
```
#container.sam_newgrid #content_left {
    width: auto;
}

#container.sam_newgrid {
    margin: 0 auto;
}

#container.sam_newgrid .hint_common_restop, #container.sam_newgrid .nums, #container.sam_newgrid #rs, #container.sam_newgrid .search_tool_conter {
    margin: 0 auto;
}
```
还是有点歪，姑且算是让双列页面能看不会挤在一起，自动翻页会失效

**Comment by Emperorxyz** [comment]
> 同样的问题,稍微看了一下,可以勾选"附加10-自定义样式",然后在里面写上
> 
> ```
> #container.sam_newgrid #content_left {
>     width: auto;
> }
> 
> #container.sam_newgrid {
>     margin: 0 auto;
> }
> 
> #container.sam_newgrid .hint_common_restop, #container.sam_newgrid .nums, #container.sam_newgrid #rs, #container.sam_newgrid .search_tool_conter {
>     margin: 0 auto;
> }
> ```
> 
> 还是有点歪,姑且算是让双列页面能看不会挤在一起,自动翻页会失效

可以的，暂时先用着这个，还可以换背景图片😎

**Comment by wolffy1998** [comment]
![image](https://user-images.githubusercontent.com/45293057/86773333-2100b080-c088-11ea-9686-ae1b32b64a76.png)zEdge这个按钮图标有点歪
