### ISSUE TITLE
提一个建议：搜索按钮后面添加一个"转谷歌",点击新打开一个页面可以看谷歌搜索结果

### ISSUE THREAD

**Issue by XingMingYue** [langren1353/GM_script#120]
提一个建议：搜索按钮后面添加一个"转谷歌",点击新打开一个页面可以看谷歌搜索结果

参考图
![image](https://user-images.githubusercontent.com/38197879/87109101-5975d980-c296-11ea-8ad8-4f92c4f2d970.png)

**Comment by sAMs126** [comment]
插件提供的功能： **优化搜索结果**

您想要的功能： **聚合搜索**

**Comment by XingMingYue** [comment]
好的
我找到了一个聚合搜索网站，很惊奇的是该插件还支持https://www.gobaidugle.com/
