### ISSUE TITLE
谷歌搜索结果 `翻译此页` 未对齐

### ISSUE THREAD

**Issue by talking-toaster** [langren1353/GM_script#122]
- 版本: v23.33
- 浏览器: Google Chrome 已是最新版本 版本 83.0.4103.116（正式版本） （64 位）
- 系统: win10 1904 x64 professional
- 脚本管理: Tampermonkey 4.10

1.原版 `翻译此页`
![原版翻译对齐](https://user-images.githubusercontent.com/49156890/87246367-8df8b980-c47f-11ea-9369-5e402cd1806a.png)
2.使用脚本后的 `翻译此页`

![翻译对不齐](https://user-images.githubusercontent.com/49156890/87246412-e62fbb80-c47f-11ea-9bfb-0bf7ff6297cb.png)

==================================================================

目前个人解决方案:
```css
.eFM0qc {
    margin-top: 11px;
}
```

**Comment by langren1353** [comment]
感谢反馈，即将推送
