### ISSUE TITLE
AC-baidu脚本设置页面无法使用。

### ISSUE THREAD

**Issue by BenjiaH** [langren1353/GM_script#124]
浏览器：Microsoft Edge版本 84.0.522.44 (官方内部版本) (64 位)
油猴：版本4.10.6111
脚本：24.0
描述：设置页面无法使用，见图
![image](https://user-images.githubusercontent.com/46958476/88484226-a4366780-cf9f-11ea-866d-bba0d4d305d2.png)

**Comment by moreant** [comment]
Edge Chrome 的 24.0 版本出现同样的问题 切换回 23.33 版本正常
![微信图片_20200727002915](https://user-images.githubusercontent.com/45537528/88484308-3c345100-cfa0-11ea-8639-e43224ac89f4.png)

**Comment by fz6m** [comment]
同，控制台显示 vue 未成功加载，先用 23.33 吧。

**Comment by langren1353** [comment]
emmm。重装试试呢。
昨天不小心推了一个本地的debug版本的代码，5分钟后覆盖了一个新版的，但是这5分钟可能导致了浏览器更新数据

**Comment by moreant** [comment]
> emmm。重装试试呢。
> 昨天不小心推了一个本地的debug版本的代码，5分钟后覆盖了一个新版的，但是这5分钟可能导致了浏览器更新数据

现在正常了👍

**Comment by BenjiaH** [comment]
> emmm。重装试试呢。
> 昨天不小心推了一个本地的debug版本的代码，5分钟后覆盖了一个新版的，但是这5分钟可能导致了浏览器更新数据

重装脚本，已经解决了
