### ISSUE TITLE
关于google搜索，分成3列和4列的时候显示不完整的问题

### ISSUE THREAD

**Issue by lyuinc** [langren1353/GM_script#125]
![QQ浏览器截图20200728074206](https://user-images.githubusercontent.com/20147193/88604043-26f71980-d0a9-11ea-9a5e-647b2945ade3.jpg)
分成3列和4列的时候显示内容不完整，比如输入计算器或者是翻译显示不完整，他们之后平均的分成3个或者是4个每个内容长一点的都不能完整的显示，但是边上还有很大的白边还可以利用，请问这边如何调整自适应或者是分成3列或者是4列的时候直接把白边的内容填充满这样就有足够的空间展示了

**Comment by langren1353** [comment]
我看了下原始网页，确实没有办法，因此有这种需求的时候建议还是直接使用双列方便一些

**Comment by langren1353** [comment]
已修复
