### ISSUE TITLE
bing搜索，自动分页出现问题

### ISSUE THREAD

**Issue by tuess** [langren1353/GM_script#126]
插件设置如图：
![image](https://user-images.githubusercontent.com/42693736/88645055-45373680-d0f6-11ea-8ea3-91ade42cfa43.png)
出现问题的地方如图：
![image](https://user-images.githubusercontent.com/42693736/88645145-5f711480-d0f6-11ea-9f78-50a0d5852049.png)

**Comment by chr56** [comment]
+1
<img width="693" alt="2020" src="https://user-images.githubusercontent.com/30681738/88877578-6adc5100-d258-11ea-811f-7f7b05fa011e.png">

**Comment by langren1353** [comment]
修复中，这个问题很快的，不用慌 P_P

**Comment by langren1353** [comment]
应该已经解决了，没搞定的话继续来开

**Comment by tuess** [comment]
> 应该已经解决了，没搞定的话继续来开

多谢大佬
