### ISSUE TITLE
点击某一个搜索结果再返回后，页面无法定位到原本点击的位置

### ISSUE THREAD

**Issue by isArtJay** [langren1353/GM_script#128]
点击某一个搜索结果再返回后，页面无法定位到原本点击的位置，而是直接定位到某一页的最下边。能增加一个功能：返回后，回到到最初点击链接的位置。吗？谢谢你的付出！

### 版本号：
24.3

### 以下我的设置截图：
![image](https://user-images.githubusercontent.com/48620527/89100332-d07f3780-d428-11ea-97f8-e4865075dcd9.png)

### 例子：
![2](https://user-images.githubusercontent.com/48620527/89100273-6bc3dd00-d428-11ea-9bc3-dce98e4dc7b9.gif)

**Comment by langren1353** [comment]
开启功能1。
功能1里面会让网页打开在新标签页，这样返回就没有影响了
