### ISSUE TITLE
护眼模式保存后失效, 仍呈默认白色背景

### ISSUE THREAD

**Issue by Issac-v** [langren1353/GM_script#131]
其实几天前就在鸭鸭跑上出现了这个问题, 但由于当时使用谷歌还无此问题, 就没报issue...结果今天全都成这样了orz

浏览器: chrome浏览器, 版本为 84.0.4147.105（正式版本） （64 位）

相关搜索引擎: 仅测试了谷歌, 百度, 必应, 鸭鸭跑, 均有此问题

具体问题表现: 选色前背景为默认的白色, 点击选色后背景变为所选的护眼色, 然后点击"保存", 页面刷新后, 背景变为默认的白色.
经测试, 其他选项均可以正常保存, 仅护眼模式无法正常显示.
![1](https://user-images.githubusercontent.com/54757860/89160198-48716d00-d5a3-11ea-879c-45eaacf38dea.png)

**Comment by langren1353** [comment]
24.5 version update!!!
try this may help

**Comment by Issac-v** [comment]
> 24.5 version update!!! try this may help

well..still the same...

**Comment by langren1353** [comment]
不至于吧，加我。1353464539
我不信还是这样的

**Comment by Issac-v** [comment]
解决了, 是我自己憨批更新玩了忘了设置orz
