### ISSUE TITLE
新版Edge浏览器中样式问题

### ISSUE THREAD

**Issue by LiJunXiao** [langren1353/GM_script#136]
1.在百度的单行居中模式下,网页最下面的相关搜索栏,并不是水平居中在页面下方，而是偏移的。

**Comment by suyin-long** [comment]
补充说明：不光是在新版Edge浏览器中样式有问题，在Chrome和火狐也有问题
Chrome和新版Edge浏览器中问题相同，如图：
![1](https://user-images.githubusercontent.com/49554285/89699111-71a14d00-d957-11ea-8d25-a480423dc923.png)
火狐问题不大，网页最下面的相关搜索栏会和最后的一条搜索内容交叉覆盖，如图：
![2](https://user-images.githubusercontent.com/49554285/89699181-df4d7900-d957-11ea-8f5a-6a852100628c.png)

希望可以修复！
