### ISSUE TITLE
从24.3开始百度一直有些问题？

### ISSUE THREAD

**Issue by samlee111** [langren1353/GM_script#141]
经常无效没有启动，最近几次更新后偶尔又能用，但还是会失效（“自定义”按钮都没显示，重定向功能无效）。现在用的是24.7，百度打开“自定义”窗口文字部分都是代码，谷歌正常。
操作系统Windows10 1909 18363.997 ，浏览器Firefox 79.0(64位)，插件Tampermonkey 4.11.6117。
尝试了清除cookies，还是会失效。

更换浏览器Microsoft Edge 版本 84.0.522.59 (官方内部版本) (64 位)，插件Tampermonkey 4.10.6111，似乎没有完全失效的情况（“自定义”按钮都能显示），重定向的功能正常，自定义样式无效，“自定义”窗口的内容显示为代码。

怀疑可能是浏览器和插件的缘故？因为在火狐上，重定向功能失效时，另一个“再见了百家号搜索结果”会同时失效

**Comment by langren1353** [comment]
https://cdn.baomitu.com/vue
能打开这个地址吗

**Comment by samlee111** [comment]
> 
> 
> https://cdn.baomitu.com/vue
> 能打开这个地址吗

可以啊完全没问题

**Comment by langren1353** [comment]
如果还是有问题的话建议加群然后私聊我
