### ISSUE TITLE
能否去除微软bing的“Get the new Microsoft Edge”广告

### ISSUE THREAD

**Issue by znue** [langren1353/GM_script#143]
希望能够添加除去微软bing的“Get the new Microsoft Edge”广告的功能
![无标题](https://user-images.githubusercontent.com/26486642/90948645-63811f80-e473-11ea-9db3-30f316eddda8.png)

**Comment by Akilarlxh** [comment]
新版Edge和Chrome的使用体验基本一致，还不会受长城困扰，为啥不直接升级试试。

**Comment by znue** [comment]
使用firefox比较多

**Comment by langren1353** [comment]
Edge的算了吧，人家好不容易的，为他打Call
