### ISSUE TITLE
谷歌搜索双列、三列、四列无法正常显示

### ISSUE THREAD

**Issue by GA-17** [langren1353/GM_script#145]
![2020-08-26 15-59-03 的屏幕截图](https://user-images.githubusercontent.com/41099827/91277231-2095b380-e7b5-11ea-8a97-562f49fc05a3.png)
选项勾上之后还会单列显示，只不过宽了些

**Comment by yanjuni** [comment]
确实，最后一个列超出了边

**Comment by langren1353** [comment]
什么浏览器，建议使用最新的chromium内核的

**Comment by yanjuni** [comment]
> 什么浏览器，建议使用最新的chromium内核的
就是谷歌浏览器

**Comment by langren1353** [comment]
> > 什么浏览器，建议使用最新的chromium内核的
> > 就是谷歌浏览器

加群我看看呢
