### ISSUE TITLE
百度首页去除广告失效

### ISSUE THREAD

**Issue by HyperClockUp** [langren1353/GM_script#147]
<img width="771" alt="失效" src="https://user-images.githubusercontent.com/36909196/91933197-ed09da80-ed1a-11ea-8213-81e807e80f33.png">
如图所示

**Comment by HyperClockUp** [comment]
发现并不是失效了，是百度很鸡贼的延迟加载广告

**Comment by langren1353** [comment]
并不是，一般来说是你没有开启功能。默认我记得功能是关闭的，你需要手动开启，在自定义里面

**Comment by HyperClockUp** [comment]
好的，确实是我没开~可能是因为重装了一下设置没了~感谢
