### ISSUE TITLE
自动预测体验改善

### ISSUE THREAD

**Issue by omyhub** [langren1353/GM_script#149]
设置自动翻页，设置延时，体验还是不太好。
预测既然能放到一个ifram或者叫区域吧，能不能去检测鼠标行为，鼠标停留在预测区域，则先不翻页，很可能是使用者在选择预测词，当鼠标不在预测区时，按照现有策略翻页，感觉这样更智能点

**Comment by langren1353** [comment]
不搞这种复杂操作的，复杂了用户也不知道怎么回事。没考虑过这种

**Comment by omyhub** [comment]
还好吧，其实就是翻页前检测鼠标是否在悬停在预测词的ifram上，是就先不执行操作，否则翻页。
不然那个要更改搜索词，用预测词替换就看手速了

**Comment by langren1353** [comment]
想法不错，但是用户不知道，我没法去引导用户知道。即功能虽然有，但是用户不会用，即无用
