### ISSUE TITLE
控制面板的高度问题

### ISSUE THREAD

**Issue by troyeguo** [langren1353/GM_script#150]
您好！感谢您开发出这么好用的脚本，我在使用过程中有一点小问题，就是控制面板底部的两个按钮保存和取消会被电脑上的任务栏挡住，每次都要手动修改浏览器的缩放比例，才能看到下面的两个按钮，才能保存设置。我的电脑分辨率是1920*1080。

**Comment by langren1353** [comment]
一般来说是因为你开启了屏幕显示缩放的原因，导致了底部的看不到，我记得我做过一些兼容。
因此如果你的确实看不到，那暂时只能手动改个缩放，然后再保存了
