### ISSUE TITLE
【反馈】多吉搜索的显示位置

### ISSUE THREAD

**Issue by troyeguo** [langren1353/GM_script#151]
开发者您好！
脚本图标在多吉搜索的显示位置好像有点问题，就像下面这张图显示的样子。
https://i.loli.net/2020/09/09/xOmoGqeQDYdjyKr.jpg

**Comment by langren1353** [comment]
看了下原因，是因为样式的原因，推荐你暂时使用其他模式来进行显示
之后我会修复这个问题

**Comment by langren1353** [comment]
已经推送24.8，待测试
