### ISSUE TITLE
几点小建议

### ISSUE THREAD

**Issue by XVCoder** [langren1353/GM_script#152]
**1. 因为有“自动翻页”功能，所以会出现有时候页面翻了很长之后，突然想转到页首重新浏览一遍的情况**
    建议在右下方显示“返回顶部”的Button

**2. 原生右侧栏的相关网站之类的虽然不怎么美观，但是“百度热榜”还算便利，搜索的同时可以看看当前的热闻也挺不错**
    建议新增“显示百度热榜”的选项

###### 另外值得一提的是，作者牛批！[破音]

**Comment by langren1353** [comment]
关于第一点，你可以多用用键盘上的Home键，我反正习惯了。
关于第二点，可以开启为单列（居中）+自定义7 侧边栏就出来了
