### ISSUE TITLE
百度搜索结果“官网”字样不可见

### ISSUE THREAD

**Issue by horsegame** [langren1353/GM_script#155]
好吧，看起来“官网”的颜色被设置为和底框的蓝色一样了……希望能修复一下。

![屏幕截图(362)](https://user-images.githubusercontent.com/43884853/92992613-cae43980-f51e-11ea-99e9-7db5d4ac5be4.png)
![屏幕截图(366)](https://user-images.githubusercontent.com/43884853/92992835-53afa500-f520-11ea-9304-300970968f11.png)
![屏幕截图(367)](https://user-images.githubusercontent.com/43884853/92993063-b9e8f780-f521-11ea-89d3-ba61e976bfd0.png)

**Comment by langren1353** [comment]
帅气的官网！~！
尽快搞定，感谢反馈，我都没发现这个尴尬的事情，啊哈哈哈哈哈

**Comment by horsegame** [comment]
秒回可还行😊感谢
