### ISSUE TITLE
搜索词时存在卡死情况

### ISSUE THREAD

**Issue by M1NGc** [langren1353/GM_script#157]
http://www.baidu.com/s?ie=UTF-8&wd=springcloudalibaba

**Comment by langren1353** [comment]
是高亮脚本那个吗

**Comment by M1NGc** [comment]
![image](https://user-images.githubusercontent.com/26264126/93063804-5b4e8580-f6a9-11ea-90a3-7d7e72647c7c.png)

**Comment by langren1353** [comment]
这个脚本是不会存在卡死情况的，如果有请直接加入私聊

**Comment by M1NGc** [comment]
[45518756bdedbbd5275ce56ce004130c.zip](https://github.com/langren1353/GM_script/files/5217182/45518756bdedbbd5275ce56ce004130c.zip)
你看一下这个视频

**Comment by langren1353** [comment]
你可以私聊我给你处理

**Comment by M1NGc** [comment]
加群了
