### ISSUE TITLE
百度显示的一些小毛病

### ISSUE THREAD

**Issue by pbxs666** [langren1353/GM_script#158]
直接上图
![图片1](https://user-images.githubusercontent.com/47630168/93109211-5956e780-f6e6-11ea-8fae-b23a4b9d3217.png)
每个选项卡的阴影浮动效果基本没了

![图片2](https://user-images.githubusercontent.com/47630168/93109275-6ffd3e80-f6e6-11ea-9772-cb8ed0460269.png)
图片上方总会显示蓝色的域名链接

![图片3](https://user-images.githubusercontent.com/47630168/93109315-80adb480-f6e6-11ea-8fe9-1c120da829f2.png)
还有相关搜索的显示有小问题，“相关搜索”这几个字左上角显示错位。

版本：24.9
其他旧版我也试过了，还是不行。应该是百度又改版了。求大佬看看是怎么回事？

**Comment by pbxs666** [comment]
![图片4](https://user-images.githubusercontent.com/47630168/93109668-eac65980-f6e6-11ea-8445-1a4f1eedbc62.png)
哦，还有一点，文字原来应该是从红框开始显示的吧，现在跳到了从蓝框位置开始显示，看起来怪怪的。

**Comment by langren1353** [comment]
已修复
