### ISSUE TITLE
Google 双列出现 translate this page跟标题重叠，极容易误点击到「translate this page」

### ISSUE THREAD

**Issue by ziventian** [langren1353/GM_script#169]
现象截图如下：
![image](https://user-images.githubusercontent.com/4437194/96205994-85da7980-0f9a-11eb-8466-5bc42287f89e.png)

附:
插件版本及配置信息如下:
![image](https://user-images.githubusercontent.com/4437194/96206076-b3272780-0f9a-11eb-9fe7-06e46970d9f9.png)

系统以及浏览器版本信息如下:
系统: Windows 10 专业版 版本号2004
浏览器: Chrome  85.0.4183.121（正式版本） （64 位）

**Comment by langren1353** [comment]
已修复
