### ISSUE TITLE
在darkreader黑暗模式下,会有边框,不知道怎么去掉,求作者告知

### ISSUE THREAD

**Issue by k650dg4d2** [langren1353/GM_script#173]
![QQ截图20201030221113](https://user-images.githubusercontent.com/32454224/97715024-daced180-1afc-11eb-87ca-4b599160d4f2.png)

**Comment by felix-klk** [comment]
附加3-自定义样式 取消勾选就行了

**Comment by k650dg4d2** [comment]
![QQ截图20201101171229](https://user-images.githubusercontent.com/32454224/97798921-7da25f80-1c65-11eb-969b-52c718afe489.png)
大佬,这个问题能不能解决一下,这个排序好像不怎么对

**Comment by langren1353** [comment]
排序不对的问题解决不了，这个排序本来就是一个不稳定的计算方法，所以解决不了的，仅做参考
