### ISSUE TITLE
百度搜索第一页中选项卡片及聚合资讯内的地址重定向无效（或未重定向）

### ISSUE THREAD

**Issue by pixiandouban** [langren1353/GM_script#177]
点击百度右侧的百度热榜，在随后的百度搜索中，第一页中会有卡片显式，卡片内的地址没有进行重定向。

截图如下所示：

1、搜索热榜->选项卡片 （搜索框下的选项卡片）
![Baidu_redirect](https://user-images.githubusercontent.com/50656651/99781984-8515a400-2b53-11eb-9c50-a1c6b7406732.PNG)

2、百度聚合资讯（最新相关消息）
![Baidu_redirect_news](https://user-images.githubusercontent.com/50656651/99784026-29004f00-2b56-11eb-95b1-803b89c4afaa.PNG)

有另一款插件叫 [anti-redirect](https://github.com/axetroy/anti-redirect) 对 `首页的卡`片 及 `最新相关消息` 添加了重定向，不过有时有些地址重定向的解析无效。

**Comment by langren1353** [comment]
考虑到这个信息不属于主流信息块，因此没有考虑加入重定向处理。
