### ISSUE TITLE
点击搜索条目会有明显的延迟

### ISSUE THREAD

**Issue by MinghaoCao** [langren1353/GM_script#18]
打开重定向，点击搜索出来的结果会有明显的延迟后才跳转

**Comment by langren1353** [comment]
推荐使用tamperMonkey，尽量暂时不用GreaseMonkey，因为GreaseMonkey暂时由于API的问题，所以说功能不全

**Comment by MinghaoCao** [comment]
用的就是油猴啊，还有就是只有百度家的网站没延迟，

**Comment by MinghaoCao** [comment]
好像是油猴更新完出的问题，把油猴插件关闭再打开就好了，
