### ISSUE TITLE
Google 引擎多列显示失效

### ISSUE THREAD

**Issue by BenjaminGao** [langren1353/GM_script#180]
Tampermonkey version: 4.11

双列，三列，四列搜索结果均失效。
![](https://i.loli.net/2020/12/03/niYs9HFI8Ngbut4.png)

**Comment by njc0125** [comment]
一样，全失效了

**Comment by xyf007** [comment]
一样，全失效了

**Comment by YadominJinta** [comment]
没失效，但是样式炸了
![image](https://user-images.githubusercontent.com/25575115/101525127-d7fdb100-39c5-11eb-958f-561275de8623.png)

**Comment by Hanlen** [comment]
MAC Chrome Version 87.0.4280.67 (Official Build) (x86_64)
双列失效，无法自动翻页

**Comment by spectop** [comment]
![image](https://user-images.githubusercontent.com/9566880/101562695-d4d4e600-3a02-11eb-8a05-da3f6b457905.png)
双列失效，卡片宽度好像还是正常的，但是全部挤在左边了

**Comment by mike652638** [comment]
没失效, 但总体宽度及列均宽度明显收窄(占页面可视宽度比例偏小)
![image](https://user-images.githubusercontent.com/21060980/101567319-9132aa00-3a0b-11eb-82c8-fcdad7aaf1cf.png)
![image](https://user-images.githubusercontent.com/21060980/101567338-9abc1200-3a0b-11eb-8d0c-27939e6d2cf7.png)

**Comment by YadominJinta** [comment]
12.10 字体变得太大了，和侧边栏重叠了

![image](https://user-images.githubusercontent.com/25575115/101747596-ab04e780-3b06-11eb-9cb8-ec365029641f.png)
