### ISSUE TITLE
界面显示只显示一半，如图

### ISSUE THREAD

**Issue by rusty-gui** [langren1353/GM_script#186]
![image](https://user-images.githubusercontent.com/63345829/101568242-4023b580-3a0d-11eb-8ea1-97e742cf12e1.png)

**Comment by LoadingZhang** [comment]
同

**Comment by AdorableJiang** [comment]
同

**Comment by Jagerx** [comment]
GOOGLE似乎在灰度测试新的网页架构，不同账号遇到的问题都不一样，我的是不论怎么设置只显示单栏，包括Stylus里跟GOOGLE相关的样式全都挂了，期待作者更新
