### ISSUE TITLE
设置选择的是双列，但只显示单列

### ISSUE THREAD

**Issue by capitalwell** [langren1353/GM_script#187]
如题，浏览器是内核版本86.0.4240.198的chromium
![image](https://user-images.githubusercontent.com/22556759/101734589-822b2500-3afb-11eb-840c-28b87c133c99.png)

**Comment by AdorableJiang** [comment]
我也遇到了同样的问题

**Comment by liukch** [comment]
相同的问题, 如果在设置里更改到双列会生效, 保存后刷新页面就变成单列了, 连居中都没有

**Comment by mike652638** [comment]
同样的问题, AC-重定向设置 24.18 百度搜索页面, 设置-主功能-重定向功能, 设置-百度双列等勾选保存无效(刷新页面后恢复为未勾选状态)
