### ISSUE TITLE
google搜索显示异常

### ISSUE THREAD

**Issue by jfnil** [langren1353/GM_script#188]
![无标题](https://user-images.githubusercontent.com/33447368/101809607-b7169680-3b52-11eb-9fd1-150c7a3a729a.jpg)

**Comment by ExLog** [comment]
Same issues here

**Comment by Jagerx** [comment]
GOOGLE似乎在灰度测试新的搜索网页架构，不同账号遇到的问题都不一样，我的是不论怎么设置只显示单栏，包括Stylus里跟GOOGLE相关的样式全都挂了，期待作者更新

**Comment by pickcherry** [comment]
我遇到的问题是，google无法两列显示。显示器是4K+200%缩放

**Comment by langren1353** [comment]
才更新，等反馈。

**Comment by Jagerx** [comment]
> 才更新，等反馈。

![image](https://user-images.githubusercontent.com/42521386/102613217-12f1a880-416d-11eb-88cc-5223252180df.png)
感谢及时更新  已经可以双列显示。

请问  当搜索结果中有视频部分的时候   只显示在左边  右侧空白是正常么？

**Comment by langren1353** [comment]
> > 才更新，等反馈。
> 
> ![image](https://user-images.githubusercontent.com/42521386/102613217-12f1a880-416d-11eb-88cc-5223252180df.png)
> 感谢及时更新 已经可以双列显示。
> 
> 请问 当搜索结果中有视频部分的时候 只显示在左边 右侧空白是正常么？

双列正常就可以了，视频将就了，有时候是这样

**Comment by Jagerx** [comment]
> > > 才更新，等反馈。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/42521386/102613217-12f1a880-416d-11eb-88cc-5223252180df.png)
> > 感谢及时更新 已经可以双列显示。
> > 请问 当搜索结果中有视频部分的时候 只显示在左边 右侧空白是正常么？
> 
> 双列正常就可以了，视频将就了，有时候是这样

https://userstyles.org/style_screenshots/180762_after.png?r=1608278745
![image](https://user-images.githubusercontent.com/42521386/102613629-c8246080-416d-11eb-9d7d-45375c775892.png)

好的，谢谢。长期用GOOGLE，以上截图数字显示方式，标签样式觉得更大气沉浸一些，可添加嘛？

https://userstyles.org/styles/180762/google-column-card-search  （该样式已失效）

**Comment by liukch** [comment]
双列显示依然失效, 在设置中临时切换双列会生效, 保存后刷新页面即失效
![image](https://user-images.githubusercontent.com/35715689/102732398-90880500-4375-11eb-8d1a-e71be05a9f19.png)
