### ISSUE TITLE
百度“搜索工具”失效

### ISSUE THREAD

**Issue by chen2233** [langren1353/GM_script#193]
[问题描述]
开启脚本后，百度用于筛选时间的搜索工具按钮无法点击。
![image](https://user-images.githubusercontent.com/57244601/102966330-a559c980-452a-11eb-8d7d-a87fa4a330f5.png)
[运行环境]
Ubuntu18.04 Win10 2004试验发现均有问题，禁用脚本后恢复正常。
Chrome内核为87，使用Tampermonkey。
百度账号未登录。

**Comment by LynahZ** [comment]
遇到了同样的问题

**Comment by cced3000** [comment]
同样问题，求解决方法，或者谁能提供上一个版本的脚本

**Comment by langren1353** [comment]
confirm.
修复中，可以稍等，之后修复

**Comment by likeya** [comment]
更新到最新版本，百度搜索结果显示变得非常慢。

**Comment by machinewu** [comment]
原因是数据判断错误，Array.prototype.acpush的方法里面data有undefined的出现
![QQ截图20201225110101](https://user-images.githubusercontent.com/4166753/103116274-dc51eb80-46a0-11eb-969b-0c237ab6b647.png)
![剪贴板图片](https://user-images.githubusercontent.com/4166753/103116278-e1169f80-46a0-11eb-8ad0-55d1b629c1ef.jpg)

只要把红圈那行
```if (data === null || data === "") return;```
改为
```if (data === null || data === "" || data === undefined) return;```
就能使用搜索工具

**Comment by EagerD** [comment]
遇到同样的问题。

**Comment by p88oo** [comment]
> 原因是数据判断错误，`Array.prototype.acpush`的方法里面`data`有`undefined`的出现
> ![控制台报错](https://user-images.githubusercontent.com/4166753/103116274-dc51eb80-46a0-11eb-969b-0c237ab6b647.png)
> ![错误位置](https://user-images.githubusercontent.com/4166753/103116278-e1169f80-46a0-11eb-8ad0-55d1b629c1ef.jpg)
> 
> 只要把红圈那行
> `if (data === null || data === "") return;`
> 改为
> `if (data === null || data === "" || data === undefined) return;`
> 可以使用搜索工具

成功解决

**Comment by langren1353** [comment]
目前更新最新版可以解决
