### ISSUE TITLE
开启重定向功能之后点击搜索的时候速度很慢

### ISSUE THREAD

**Issue by zyc2056** [langren1353/GM_script#194]
开启重定向功能之后点击搜索的时候速度很慢大概2-3秒出结果，关闭之后速度很快，点后就出。

**Comment by MikeyShell** [comment]
同有这个问题，没有开启重定向的勾，最近一次更新脚本后百度搜索就变慢了，约4秒，关掉正常。

**Comment by 928718283** [comment]
![image](https://user-images.githubusercontent.com/56189619/103147279-e81bdb80-478e-11eb-9e1c-a7212a5d3009.png)

同有这个问题

**Comment by MasterOfStar** [comment]
同问题

**Comment by zyc2056** [comment]
应该AC-baidu 这个脚本写的有问题

**Comment by langren1353** [comment]
更新啊，说那么多干啥
