### ISSUE TITLE
百度搜索，广告、单列居中 有问题

### ISSUE THREAD

**Issue by TlgYuri** [langren1353/GM_script#212]
baidu搜索，打开广告过滤，右侧广告推荐、热门列表没被屏蔽。
选择单列居中模式，右侧被推荐内容占据，搜索结果并没有居中

如果考虑到有人想看右侧的广告和热门推荐，建议添加一个对应的开关选择是否显示

**Comment by wuruiqi** [comment]
同样问题，单列显示模式下，百度搜素热榜依然显示。双列以上就没有这个问题了。

**Comment by Ming-Yang** [comment]
同样问题，期待修复

**Comment by langren1353** [comment]
附加7
