### ISSUE TITLE
多列展示点击整个框可以进入

### ISSUE THREAD

**Issue by akangwu** [langren1353/GM_script#223]
![image](https://user-images.githubusercontent.com/43903377/109405347-aab01600-79aa-11eb-8bd6-faab0a1faf74.png)

**Comment by langren1353** [comment]
谢谢建议，不过这个暂不考虑，主要是考虑到很多人更希望的是原有的点击模式，对比很多搜索引擎，极少有点击整个进行跳转的，希望理解
