### ISSUE TITLE
为什么会出现失效的情况

### ISSUE THREAD

**Issue by carrot117** [langren1353/GM_script#224]
百度会出现脚本失效的情况，会变成原来的样子，但是刷新一下就可以了，但是在edge上没有这种问题，只有在chrome上出现了，浏览器，脚本，插件都重装过了
![image](https://user-images.githubusercontent.com/73765226/109590695-65751b00-7b47-11eb-94de-3566b3278530.png)

**Comment by langren1353** [comment]
附加6 记得勾选上。一般是打开百度后，开始搜索，但是附加6没开，页面自动加载，然后没有触发进一步内容更新

**Comment by carrot117** [comment]
> 附加6 记得勾选上。一般是打开百度后，开始搜索，但是附加6没开，页面自动加载，然后没有触发进一步内容更新

感谢
