### ISSUE TITLE
使用百度搜索样式不会立即生效，需要点一下刷新才生效？

### ISSUE THREAD

**Issue by suyin-long** [langren1353/GM_script#227]
现在使用百度搜索后设定的样式不会立即生效，如图：
![1](https://user-images.githubusercontent.com/49554285/110465087-f2ebd880-810e-11eb-9840-6aef0b1498d5.png)
手动点击一下刷新后才会生效，如图：
![2](https://user-images.githubusercontent.com/49554285/110465197-144cc480-810f-11eb-8b62-b09013d45d95.png)
这是怎么回事？

**Comment by MasterOfStar** [comment]
#207 看起来可能是一样的问题？

**Comment by langren1353** [comment]
附加6功能开一下
