### ISSUE TITLE
搜索结果页，全宽度下，顶部栏适配偏差

### ISSUE THREAD

**Issue by JasonLamv-t** [langren1353/GM_script#228]
![image](https://user-images.githubusercontent.com/39087996/110649548-aaa6e600-81f4-11eb-92c0-ece2867e3e70.png)

**Comment by langren1353** [comment]
这个我确实尽力了。。。没有4K的屏幕。。适配凭感觉的

**Comment by JasonLamv-t** [comment]
﻿诶，我的屏幕不是4k的，是1080p的，而且笔记本上看正常，只有mini上看不正常


发自我的iPhone

在 2021年3月24日，11:36，langren1353 ***@***.***> 写道：

﻿

这个我确实尽力了。。。没有4K的屏幕。。适配凭感觉的

**Comment by astinx** [comment]
我2k, 我改了好多样式错乱的问题, 看这个 https://github.com/langren1353/GM_script/issues/243 , 别拿引用的, 因为那个我改过
