### ISSUE TITLE
可以设计每次搜索后，自动执行点击“工具”->“时间不限（点击更改为过去一年内）“吗？

### ISSUE THREAD

**Issue by zfhxi** [langren1353/GM_script#235]
可以设计每次搜索后，自动执行点击“工具”->“时间不限（点击更改为过去一年内）“吗？这样每次搜索的结果按时间排序，希望看到最新的资料。

**Comment by langren1353** [comment]
这个并不是常用的方法，故暂时不考虑，感谢你的建议
