### ISSUE TITLE
百度Lite样式有问题

### ISSUE THREAD

**Issue by OriginalReimu** [langren1353/GM_script#25]
百度翻译文字超框了https://i.loli.net/2019/05/26/5cea42a3e6cad58708.png
[](https://i.loli.net/2019/05/26/5cea42a3e6cad58708.png)

**Comment by MeteorInfinity** [comment]
我这里与Stylus上的BaiduLite有冲突，屏蔽百家号功能失效，自定义消失；
插件里的Lite样式各种超框、不对应
