### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by usjinbao** [langren1353/GM_script#26]
建议在增加过黑名单以后不要让当前页显示结果数量减少而是把后面的数量凑上来补全。
现在的情况很不舒服，比如我百度搜索设置了每页显示50条结果，其中49条的地址是以前就被block的，那么搜索过滤后当前整个页面就仅仅显示1条搜索结果，这用起来很麻烦。

**Comment by joseph4syn** [comment]
感觉这个应该不行，分页内容的多少是百度返回的。除非 插件通过分页多请求一些内容 然后把多的加入到隐藏域， 不过从网页响应的过程看 应该是拿到结果插件只是过滤一下…

**Comment by langren1353** [comment]
上面的这个小伙伴已经很好的回答了这个问题，数量缺少之后想要补全是不可能的，否则会一直触发页面加载
