### ISSUE TITLE
不知道哪部分是谷歌单列居中的样式？

### ISSUE THREAD

**Issue by xiaozixun** [langren1353/GM_script#262]
我想找出来单做个样式，结果发现我找不到……

**Comment by langren1353** [comment]
// @resource  googleCommonStyle  http://ibaidu.tujidu.com/newcss/googleCommonStyle.css?t=24.21
// @resource  googleOnePageStyle http://ibaidu.tujidu.com/newcss/googleOnePageStyle.css?t=24.21
// @resource  googleTwoPageStyle http://ibaidu.tujidu.com/newcss/googleTwoPageStyle.css?t=24.21

**Comment by xiaozixun** [comment]
> 
> 
> // @resource googleCommonStyle http://ibaidu.tujidu.com/newcss/googleCommonStyle.css?t=24.21
> // @resource googleOnePageStyle http://ibaidu.tujidu.com/newcss/googleOnePageStyle.css?t=24.21
> // @resource googleTwoPageStyle http://ibaidu.tujidu.com/newcss/googleTwoPageStyle.css?t=24.21

十分感谢
