### ISSUE TITLE
反馈：关于baidu搜索条目垃圾推广影响排版

### ISSUE THREAD

**Issue by controlledentropy** [langren1353/GM_script#270]
希望诸位大佬更新样式规则，增加屏蔽百度垃圾推广结果。
现行的过滤规则只能隐藏正经的搜索结果条目。

这个垃圾html.cn手动加入黑名单也不能避免该推广块的出现
![image](https://user-images.githubusercontent.com/11594997/118764966-f046f580-b8ac-11eb-97cd-fc8bc5ae7d2c.png)

还有这种智能聚合
![image](https://user-images.githubusercontent.com/11594997/118765618-e96cb280-b8ad-11eb-8bd4-5c44a20ff78c.png)

**Comment by langren1353** [comment]
这种属于正常搜索结果，预计之后也不会对这种数据进行删除（主要我也没办法较好的判断是否xxx，对于某些人来说这种反而更容易获取新数据）
