### ISSUE TITLE
百度搜索界面图片框显示问题。

### ISSUE THREAD

**Issue by JedSunCN** [langren1353/GM_script#29]
如图，图片框中图片会出现缺失，空白。

![image](https://user-images.githubusercontent.com/41063651/59089841-b4bff480-893d-11e9-8b98-0cd4a28a996c.png)
![image](https://user-images.githubusercontent.com/41063651/59089889-cdc8a580-893d-11e9-87d4-3ad3c71b938d.png)

**Comment by langren1353** [comment]
确实是个bug，由于每个横行的长度不够，图片无法完整的在一行显示，所以出现了分行，出现了三行数据，预计下个版本修复

**Comment by langren1353** [comment]
已经解决了V23.22
