### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by nengqi** [langren1353/GM_script#30]
- Google搜索样式选择单列以后，即使勾选了显示右侧栏，右侧栏还是会被挤掉，这应该算个bug😂。实际上有的时候右侧的相关联想还是挺好用的，

- 个人感觉去除百度搜索的搜索热点（保留右上方相关联想）可以单列出来作为一个feature

- 开启自定义页面样式后，页面超好看，但是各个搜索结果之间的割裂感也强了，特别是相邻两条结果之间相距过宽，导致相同面积网页下能够浏览的有效信息变少1-2条（尤其是Google）。所以希望考虑在“附加10:自定义样式”代码框里添加更改两条搜索结果之间间距，边框宽度等一些信息，或者其他实现方法

**Comment by langren1353** [comment]
由于屏幕过小，单列居中之后，右侧不足以放下实际的右侧栏，故会被隐藏掉，想要不隐藏换大屏幕，同理对于问题三，至于问题二暂时不考虑
