### ISSUE TITLE
自定义样式 设定背景问题

### ISSUE THREAD

**Issue by MC-dusk** [langren1353/GM_script#301]
看了 #210 #297 ，使用本地图片是不行了，但能不能使用纯色背景呢？如下：

```
/****可以加一些自己的背景图片,替换引号内的内容为可外链的图片即可****/
body{
background-color:#F5ECCE;
}
```

~~不知道为什么没有效果，html网页背景色应该是这么设定的吧~~

刚刚偶然发现是有效果的，比如bing搜索，背景色已经变了。
但百度、谷歌仍然不行。

另外有时图片加载不出来，特别是配合[快捷切换搜索引擎脚本](https://github.com/qxinGitHub/searchEngineJump)使用的时候。

```
/****可以加一些自己的背景图片,替换引号内的内容为可外链的图片即可****/
body{
  background-repeat: repeat-y;
  background-size: 100%;
  background-attachment: fixed;
  background-image: url('...');
}
```

**Comment by langren1353** [comment]
图片加载不出来不是脚本的问题；
更多情况是脚本加载慢、脚本禁止外链

**Comment by MC-dusk** [comment]
> 图片加载不出来不是脚本的问题；
> 更多情况是脚本加载慢、脚本禁止外链

那请问纯色背景又是什么问题呢？连知乎都是有效的

**Comment by langren1353** [comment]
> > 图片加载不出来不是脚本的问题；
> > 更多情况是脚本加载慢、脚本禁止外链
> 
> 那请问纯色背景又是什么问题呢？连知乎都是有效的

那属于前端问题，不同的网页实现不同，纯色背景更容易导致页面不同地方依然有色块，这也就是为什么纯色背景最近这些年才出现，得要目标网站做一定的适配，否则就是强制覆盖
