### ISSUE TITLE
走势图不知道是否被脚本屏蔽了,有的有 有的没有走势

### ISSUE THREAD

**Issue by M1NGc** [langren1353/GM_script#302]
![image](https://user-images.githubusercontent.com/26264126/126253970-c44419b4-9c1d-431e-b984-1561914d930e.png)
![image](https://user-images.githubusercontent.com/26264126/126253977-664fc13d-179e-4263-b08d-60bb8782b162.png)

**Comment by langren1353** [comment]
OK，已经加入自选了 P_P
哈哈哈哈，我也是才发现好像没有走势图的，到时候抽时间看看能不能修复试试

**Comment by M1NGc** [comment]
![image](https://user-images.githubusercontent.com/26264126/128136775-87fc1854-eb14-4e50-8fec-da648bac4a3d.png)
三安买了吗

**Comment by langren1353** [comment]
嗨呀，我其实根本不买股票，所以没事，哈哈哈哈
我有一部分的芯片etf
