### ISSUE TITLE
谷歌带视频的搜索结果页面触发自动翻页后会出错

### ISSUE THREAD

**Issue by ScrapW** [langren1353/GM_script#312]
![image](https://user-images.githubusercontent.com/19533993/129196840-28f18c9a-42fc-4027-aad4-0d21fb4b134e.png)
此时点击灰框任意位置都会跳转到其中某一个网页

**Comment by kukusyaoran** [comment]
出现同样问题，希望能有解决方法

**Comment by langren1353** [comment]
已修复
