### ISSUE TITLE
#316 画线在bing不起作用

### ISSUE THREAD

**Issue by Joseph-zheng** [langren1353/GM_script#316]
![image](https://user-images.githubusercontent.com/18510737/130565148-4fc6229c-bb17-4a4c-9326-76656203ad0c.png)
百度：右侧栏怎么设置都会出现，右边栏去不掉
bing:  图标会重复，无法编号，无法下划线，右边栏去不掉
谷歌：无法下划线，右边栏无法去掉

**Comment by langren1353** [comment]
空了修。
只是最近不得空，所以一直拖着

**Comment by langren1353** [comment]
反正mark了，到时候抽时间搞搞
