### ISSUE TITLE
百度干掉了MutationObserver，翻页时监听器出错了，链接的点击事件加不上，搜索结果没法跳转了。

### ISSUE THREAD

**Issue by leitingx762** [langren1353/GM_script#318]
![image](https://user-images.githubusercontent.com/5674953/131249223-ed58b269-0545-4ad4-9a66-bbfc91072858.png)

**Comment by langren1353** [comment]
我记得我没用过MutationObserver了，以前
// @note    2017.03.19-V7.2 未知原因chrome的MutationObserver无法使用了，继续回归以前的DOMNodeInserted
这个版本的时候就没用这个功能了

**Comment by Yu-L-Fan** [comment]
这个问题解决了吗 今天突然也出现这情况 之前还好好的

**Comment by leitingx762** [comment]
不好意思， 是我看错了。
MutationObserver是其他插件调的。
当时没细看，因为是触发自动翻页后才不正常，我就把ac-baidu关了。
然后试了下，打开插件，每次触发翻页都出问题。
看了下控制台报错 MutationObserver 被重写了，我就没细查了。。。。
