### ISSUE TITLE
百度lite样式问题

### ISSUE THREAD

**Issue by Dash2KoF** [langren1353/GM_script#32]
启用百度lite样式后,搜索框无法进行输入操作,在userstyles.org网站上的百度lite主题也试过,一样不能进行键入. 浏览器用的是Edge canary 和Chrome.系统是 1903

**Comment by zhangrickStudio** [comment]
百度lite样式 搜索栏不是居中的 一边多一边少

**Comment by shanyujie** [comment]
启动百度lite模式后在，百度搜索主页（https://www.baidu.com/）的样式和lite模式的样式重叠了，两个百度图标叠在一起，没有覆盖成功

**Comment by shanyujie** [comment]
<img width="1438" alt="屏幕快照 2019-07-28 下午5 36 46" src="https://user-images.githubusercontent.com/22969676/62004955-b4362400-b15e-11e9-98b4-2c9f07db4271.png">
lite模式真的好看，但是百度搜索首页现在样式不对了<img id="s_lg_img_new">应该删除这个标签

**Comment by shanyujie** [comment]
<img width="1438" alt="屏幕快照 2019-07-28 下午5 36 46" src="https://user-images.githubusercontent.com/22969676/62004963-d4fe7980-b15e-11e9-9551-919b3c7eec9f.png">
百度lite模式很好看，但是现在样式不对了,要删除一个img标签，标签id和class如下
 id="s_lg_img_new" class="s_lg_img_gold_showre"

**Comment by shanyujie** [comment]
还有输入框的位置和百度的图标的位置好像不太居中对齐
