### ISSUE TITLE
适配chrome深色模式

### ISSUE THREAD

**Issue by shutonglifo** [langren1353/GM_script#323]
当chrome开启深色模式，使用AC的搜索结果列表中的每个搜索块的底色就会过于亮眼，希望能够适配深色模式。
同时，自定义按钮颜色也过于亮眼，最好能一起做调整，谢谢

**Comment by langren1353** [comment]
深色模式，可以配合darkreader一起使用，脚本不再做单独的兼容了，因为确实不好做
