### ISSUE TITLE
点击Favicon有打开设置界面的EventListener？

### ISSUE THREAD

**Issue by hmpthz** [langren1353/GM_script#359]
看了一下源码，发现打开了Favicon后，点击搜索项左边的Favicon会打开设置界面，不知道这个功能的作用是什么呢？
本来是无关紧要的，但我目前在使用surfingkeys这个扩展（[edge链接](https://microsoftedge.microsoft.com/addons/detail/surfingkeys/kgnghhfkloifoabeaobjkgagcecbnppg) [chrome链接](https://chrome.google.com/webstore/detail/surfingkeys/gfbliohnnapiefjpjlpjnehglfpaknnc)）。其中在google搜索时surfingkeys会把链接识别到左边的Favicon上，这样点击时就会打开设置界面，如下图所示
![Screenshot](https://user-images.githubusercontent.com/44091340/141763280-fbc844e2-189e-45dd-8e4e-a5e51094785a.png)
其实问题也不大，只要点击上面的那个网址链接就能正常打开了，算不上issue，只是反馈一下而已

**Comment by langren1353** [comment]
就是有些人会隐藏掉‘自定义’按钮，然后又找不到自定义面板做的一个兼容
如果你觉得这个东西有一定的影响的话，可以尝试关掉favicon按钮即可

**Comment by brother-darion** [comment]
> 

成年人不能都要吗，favicon很直观，也不想跳出设置。我就是隐藏掉“自定义”按钮的，自定义面板可以通过Tampermonkey设置那里可以点开。
