### ISSUE TITLE
怎么使用通配符屏蔽同子域名网页？

### ISSUE THREAD

**Issue by wh5683** [langren1353/GM_script#39]
怎么批量匹配屏蔽掉？ 
如：
https://chrome.en.softonic.com/ 
https://teamviewer.en.softonic.com/
屏蔽掉所有以en.softonic.com结尾的这类网站
*.en.softonic.com，这样配置没用。

**Comment by langren1353** [comment]
暂时没有使用通配符来进行域名的校验，因为很容易出错误导致异常的隐藏了某些正常网页，故不开启通配符模式
