### ISSUE TITLE
请问可以禁止百度搜索视频大全和全网热卖？

### ISSUE THREAD

**Issue by chikungfu** [langren1353/GM_script#397]
![1](https://user-images.githubusercontent.com/51909833/146701053-f82cd45a-0663-4df1-a121-8acf00723c15.png)

**Comment by chikungfu** [comment]
![2](https://user-images.githubusercontent.com/51909833/146701205-93627853-fd56-4ad1-8720-81f4c807b8a6.png)

**Comment by 2SHANINGITHUB** [comment]
+1

**Comment by langren1353** [comment]
这个暂不考虑，因为这个属于人正常的检索结果，只是对于某些用户不需要
