### ISSUE TITLE
Bing 单列居中模式页面布局问题

### ISSUE THREAD

**Issue by mymartin** [langren1353/GM_script#40]
Bing 国际版和国内版单列居中模式，搜索建议条目也会居中。
![搜索建议条目居中](https://user-images.githubusercontent.com/6276117/63069049-0d1bff80-bf48-11e9-9667-f53cc7b07645.png)

其中，国际版中“翻译成中文”和“开启取词”两个按钮会遮住类别。
![搜索类别被遮住](https://user-images.githubusercontent.com/6276117/63069119-4e141400-bf48-11e9-9b05-9bf40f7b5d1c.png)

脚本的设置如下
![图片](https://user-images.githubusercontent.com/6276117/63069271-df838600-bf48-11e9-94b5-cffb4104d40d.png)

**Comment by langren1353** [comment]
必应已经修复
