### ISSUE TITLE
能否屏蔽百度全网热卖结果

### ISSUE THREAD

**Issue by 2SHANINGITHUB** [langren1353/GM_script#407]
![QQ截图20220105130259](https://user-images.githubusercontent.com/90484463/148163290-aafde0a2-751b-4920-9189-1f18afed257d.png)

**Comment by langren1353** [comment]
这个输入百度正常的搜索检索结果，适用于不同的人群，暂不考虑屏蔽

**Comment by 2SHANINGITHUB** [comment]
可以考虑在自定义面板做一个开关，默认显示，不需要的人群可以打开开关屏蔽此类结果
