### ISSUE TITLE
能否加个搜索选项“一件过滤csdn结果”

### ISSUE THREAD

**Issue by hzhgino** [langren1353/GM_script#409]
经常在搜索一些技术类的信息时候，需要在搜索框手动输入 “-csdn”来过滤垃圾结果，能否考虑一下，加个搜索参数追加的功能，在搜索的时候，自动最佳这些参数，
例如，我搜索：java教程， 然后实际的搜索，就是： java教程 -csdn

**Comment by langren1353** [comment]
谢谢功能，暂不考虑
