### ISSUE TITLE
如何屏蔽百度百科

### ISSUE THREAD

**Issue by zhiai0yueru** [langren1353/GM_script#41]
百度看都不想看一眼, 其他产品(如知道/经验)可以屏蔽, 除了这个百度百科. 

baidu.com
baike.baidu.com
*.baidu.com
以上三个自定义域名都不能屏蔽掉百度百科, 也没有block按钮. 

另: 可否直接去掉已屏蔽的空白长条, 如: 
![image](https://user-images.githubusercontent.com/30485140/63219252-3f279e80-c1a0-11e9-933c-d65493ab4c1d.png)

谢谢!

**Comment by langren1353** [comment]
百度百科的东西比较特殊，不好做统配，故技术上没能添加上block按钮，如果不喜欢百度的东西建议可以使用其他搜索引擎
