### ISSUE TITLE
反馈-Chrome暗黑模式下必应搜索闪烁

### ISSUE THREAD

**Issue by ZHJ0125** [langren1353/GM_script#418]
## 问题描述
开发者您好，我尝试在Chrome暗黑模式下使用此脚本，在必应搜索页面，当鼠标掠过搜索结果框时，会出现短暂的白色闪烁。

## 问题截图
http://47.95.13.239/data/image/img2.gif

## 问题复现
>* AC-baidu版本：25.01
>* 操作系统：Win10
1. Chrome浏览器，地址栏输入`chrome://flags/#enable-force-dark`，开启`enable-force-dark`。
2. 开启AC-baidu脚本，进入必应搜索页面（ https://cn.bing.com ）。
3. 当鼠标掠过搜索结果框时，会出现短暂的白色闪烁。

![img1](http://47.95.13.239/data/image/img1.jpg)

希望开发者能帮忙看一下，感谢 🤞

**Comment by langren1353** [comment]
测试了一下，暂时无法复现

**Comment by ZHJ0125** [comment]
我卸载并重新安装了Chrome，问题解决了。。😂😂
感谢开发者 ✌
