### ISSUE TITLE
每次关闭浏览器重新打开，进行搜索相关操作都会使自定义按钮样式错乱，需要点击脚本设置内的保存按钮后,相关操作才能正常使用

### ISSUE THREAD

**Issue by ualroy** [langren1353/GM_script#420]
![屏幕截图 2022-01-22 193008](https://user-images.githubusercontent.com/98215583/150637226-04ea235b-368d-406e-917d-8d1f6417eacc.png)

**Comment by ualroy** [comment]
Chrome 97.0.4692.99 
Tampermonkey 4.13
已排除其他插件问题

**Comment by langren1353** [comment]
附加6，开启应该就好了
