### ISSUE TITLE
require中的”https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/less.js/4.1.2/less.min.js“ 404了

### ISSUE THREAD

**Issue by leohu1** [langren1353/GM_script#425]
![404](https://user-images.githubusercontent.com/47905372/152538314-5eb31012-8031-4210-afa3-86c8001d46fb.PNG)

**Comment by langren1353** [comment]
感谢告知，还好还有个备份的less.js，否则就尬了
字节的CDN我之后还是不用算了
