### ISSUE TITLE
谷歌搜索结果可否支持毛玻璃效果

### ISSUE THREAD

**Issue by EchoGroot** [langren1353/GM_script#431]
+ 百度搜索结果里的就有，原本想自己调整下样式，但是需要修改的地方太多，不好搞
+ 自定义样式里的不生效
```
body[google] .c-container{
  border-radius: 5px;
  background-color: rgba(255,255,255, 0.3) !important; /*百度搜索块体的颜色；透明度=0.1，最大1*/
}
```

![image](https://user-images.githubusercontent.com/44628981/153140139-27b7c138-cff6-49c1-9d7a-67b8ebb52786.png)
![image](https://user-images.githubusercontent.com/44628981/153140194-f62d6b56-0097-45f1-8301-ba71c66fd462.png)

**Comment by langren1353** [comment]
参考内容：
```
body[google]:before {
  position: fixed;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  content: '';
  background-image: url('https://img.tujidu.com/image/5fdde8468423e.jpg');
  background-size: 100% auto;
  opacity: 0.8; /*背景图透明度=0.8，最大1*/
}
#rso .g {
background-color: rgba(248,248,248, 0.6) !important; 
}
```

**Comment by langren1353** [comment]
主要是你改错东西了。这里毛玻璃的原理是：
1.在body上增加一个遮罩，这个遮罩全屏，带背景图，增加一定程度的透明度
2.修改原有白色块体的颜色，使其透明，能看到背景

最终两者结合形成了一个毛玻璃的效果

**Comment by EchoGroot** [comment]
好使  谢谢
![image](https://user-images.githubusercontent.com/44628981/153716851-26d0fd6e-e759-475e-86b7-97ec82280e80.png)
