### ISSUE TITLE
拦截列表满一页后删除按钮排版混乱，无法正确删除【bug】

### ISSUE THREAD

**Issue by horizon98** [langren1353/GM_script#45]
在使用拦截域名功能后，如果列表中拦截的域名超过了一页（即已经可以使用滚动条），无法正确移除域名，如下图所示。
![image](https://user-images.githubusercontent.com/48114360/64695806-91be5700-d4cf-11e9-8bc0-86355bb46089.png)

**Comment by langren1353** [comment]
感谢反馈，我将会在下个版本进行修复，非常感谢
