### ISSUE TITLE
屏蔽域名支持正则表达式（或其他自定义规则）

### ISSUE THREAD

**Issue by taozhiyu** [langren1353/GM_script#459]
例如希望屏蔽类似于：
https://www.csdn.net/tags/
这样的链接但是不想屏蔽csdn

**Comment by taozhiyu** [comment]
![image](https://user-images.githubusercontent.com/49258735/159613219-1d03a3c7-00b2-44e4-afce-8c813bb9ae64.png)

此外左侧主界面界面显示异常，
右侧多出”热搜“（未开启右侧栏，测试非单列该部分均正常）

**Comment by taozhiyu** [comment]
只有第一页上的屏蔽起作用，
自动翻页后的页面都不会屏蔽掉

**Comment by aronlou** [comment]
是的，屏蔽已经失效了，不能用，而且没有block按钮了。
