### ISSUE TITLE
遇到 用户还搜索了... 排版错位

### ISSUE THREAD

**Issue by domeniczz** [langren1353/GM_script#468]
<img width="901" alt="error" src="https://user-images.githubusercontent.com/42294390/161430277-94fdffb5-74a0-44b2-a30d-719c66bbaf57.png">

**Comment by FeiLZX3Km** [comment]
可能我的更严重些
![20220404102808](https://user-images.githubusercontent.com/21981195/161464216-f211a56e-ff18-4229-a112-75249e696e87.png)

**Comment by Slinet6056** [comment]
这个问题解决了吗，我现在每个连接点开后都会出现这个问题

**Comment by FeiLZX3Km** [comment]
> 这个问题解决了吗，我现在每个连接点开后都会出现这个问题

后来就卸载没再用了。
