### ISSUE TITLE
万人血书跪求屏蔽360网页域名

### ISSUE THREAD

**Issue by BBSMLtd** [langren1353/GM_script#469]
实测，几乎所有广告插件(ac百度、ubock origin、adblock等)对360域名网页（包括但不限于https://hao.360.com、so.com、360.com、360.cn等）广告无效，请问作者可否开发或定制开发？

**Comment by langren1353** [comment]
没太多的时间做新功能，所以目前都只是缝缝补补一年又过一年，将就用了。主力还是谷歌+百度，其他的兼容性都有问题，新的暂时也不想加了
