### ISSUE TITLE
google 搜图等页面UI错误

### ISSUE THREAD

**Issue by Waynehfut** [langren1353/GM_script#47]
在搜索框那块，自定义按钮跑到左侧去了
![微信截图_20190912113500](https://user-images.githubusercontent.com/8127447/64798830-a7746080-d551-11e9-8e2a-130eaa87afe4.png)
![微信截图_20190912113614](https://user-images.githubusercontent.com/8127447/64798834-a9d6ba80-d551-11e9-9c13-7615aba516e6.png)
![微信截图_20190912113623](https://user-images.githubusercontent.com/8127447/64798838-ab07e780-d551-11e9-81e4-7983b6841408.png)
感谢作者~！

**Comment by langren1353** [comment]
感谢反馈，将于近期开展修复

**Comment by langren1353** [comment]
已经修复
