### ISSUE TITLE
建议新增搜索页背景可以用必应每日壁纸的api

### ISSUE THREAD

**Issue by Uiisland** [langren1353/GM_script#477]
自己html小白，直接在自定义里修改了背景的链接地址，但是性能方面不知道怎么去优化，每次搜索都会加载3秒左右的背景图
大佬能把这个建议加进去吗？

**Comment by langren1353** [comment]
用这个接口试试：https://bing.ioliu.cn/v1
这个接口有二次访问的时候缓存，所以理论上不会出3秒加载
当然你可以找找其他接口正常访问带缓存304的那种就行
