### ISSUE TITLE
建议将百度的搜索框与搜索结果对齐

### ISSUE THREAD

**Issue by horizon98** [langren1353/GM_script#48]
![image](https://user-images.githubusercontent.com/48114360/64866613-59a14a80-d66e-11e9-9c43-3acb810e34a5.png)
搜索框正好与搜索结果偏了一个百度logo的距离
原版：
![image](https://user-images.githubusercontent.com/48114360/64866695-8190ae00-d66e-11e9-9e4a-3d8d51e47582.png)

**Comment by langren1353** [comment]
额。这个东西各有爱好吧，我的标准是这样居中的，如果你觉得不好看，你可以尝试自己修改，或者切换为lite+原始模式
