### ISSUE TITLE
开启此插件导致浏览器反应缓慢

### ISSUE THREAD

**Issue by rxl1** [langren1353/GM_script#496]
当我开启此插件时，比如在百度上搜索天气，大部分内容已经加载，但是还是在转圈，点击其它部分暂时没反应，等到过个三秒左右，刚才点击的部分才能打开新网页，此时网页才完全加载完毕，以前没出现这种问题。关闭插件时，大约0.5s页面就完全加载完成。

**Comment by 1870332922** [comment]
尝试关闭【自定义样式】？
