### ISSUE TITLE
与插件DarkReader 一起使用时，出现护眼模式的边框

### ISSUE THREAD

**Issue by Scriptbeta** [langren1353/GM_script#51]
![picture](https://user-images.githubusercontent.com/23139793/66258109-eeade400-e7d3-11e9-8a9b-7d2960429975.png)
![picture2](https://user-images.githubusercontent.com/23139793/66258173-6da31c80-e7d4-11e9-8871-7bb34a24659d.png)

如图
与插件DarkReader 一起使用时，出现护眼模式的边框

**Comment by langren1353** [comment]
这个边框是我考虑过后的，如果不加上边框，整个全黑的页面其实并不好看，故希望理解

**Comment by Scriptbeta** [comment]
emm 是颜色问题，绿色并不和谐。。（这个貌似和DR的算法有关，不知道能不能兼容

**Comment by Scriptbeta** [comment]
已经去DR那 提了pr了

**Comment by TTTPOB** [comment]
另一个问题是如果打开双栏样式就会出现一片白色
![image](https://user-images.githubusercontent.com/19909103/72581022-d8f2a380-3918-11ea-9e6e-1e07722c0791.png)
