### ISSUE TITLE
Google 排版错误

### ISSUE THREAD

**Issue by hiiiha** [langren1353/GM_script#518]
![www google com_search_q=infrared+ sxsrf=ALiCzsbI1XBdcKUQYmtdaXfIwi725vxQwg%3A1658287494063 ei=hnXXYpmNA-7P2roPreyTuAg ved=0ahUKEwiZ6JKowob5AhXup1YBHS32BIcQ4dUDCA4 uact=5 oq=infrared+ gs_lcp=Cgdnd3Mtd2l6EANKBAhBGABK](https://user-images.githubusercontent.com/77280190/179890198-1cfac8ed-74d9-45f5-b226-a6b19f835660.png)

如图
谷歌最左边只有一个搜索结果，但是右边有很多，不管是单列、居中、双列...都有这个问题

**Comment by 3biubiu** [comment]
`div[role="complementary"] {
    display: none !important;
}`  
添加自定义样式
去除右侧摘要
