### ISSUE TITLE
[功能建议] 隐藏google featured snippets

### ISSUE THREAD

**Issue by Solar-Lancelo** [langren1353/GM_script#52]
可以隐藏掉google结果页面的:
- People also ask
- Videos
这些东西吗?
![DeepinScreenshot_select-area_20191014232520](https://user-images.githubusercontent.com/52375886/66763151-ed6a6e80-eed9-11e9-857e-27c07b292072.png)
![DeepinScreenshot_select-area_20191014232456](https://user-images.githubusercontent.com/52375886/66763152-ed6a6e80-eed9-11e9-8aa1-8afe0868a6e6.png)

**Comment by langren1353** [comment]
这个是谷歌的搜索建议，故暂时不考虑关闭。
非常感谢你的反馈
