### ISSUE TITLE
两个个bug

### ISSUE THREAD

**Issue by AelepantB** [langren1353/GM_script#521]
![image](https://user-images.githubusercontent.com/104605918/181035177-45d5cba4-ac6a-497a-b085-22e68f8073b7.png)
![image](https://user-images.githubusercontent.com/104605918/181035237-77066e5e-3b6a-42fe-82ab-31fede050123.png)

**Comment by langren1353** [comment]
第一个是我的问题 - 预计新版修复，第二个得和原作者反馈了，我这边不支持这个切换功能
