### ISSUE TITLE
google双列模式显示存在一定问题，版面没有完全利用

### ISSUE THREAD

**Issue by HZYbest123** [langren1353/GM_script#529]
![image](https://user-images.githubusercontent.com/106685665/184495457-1a364972-aae5-4a81-aa79-7f07f4dbaf75.png)
![image](https://user-images.githubusercontent.com/106685665/184495478-73d2cd7a-812f-46b2-a63b-7eee100c8fbd.png)

**Comment by HZYbest123** [comment]
搜索一些影视作品的时候就会出现这种情况，大部分的搜索结果双列是正常的。

**Comment by langren1353** [comment]
感谢反馈。下一版本修复
合并与 #516
