### ISSUE TITLE
`进入搜索结果界面`到`脚本效果出现`之间存在较大延迟

### ISSUE THREAD

**Issue by ZiuChen** [langren1353/GM_script#536]
近1-2天Chrome浏览器进入搜索界面后，脚本不会立刻生效，而是在滚动页面浏览一会后才生效。

> 使用百度搜索Vercel，脚本的样式不会立即生效

![image](https://user-images.githubusercontent.com/64892985/187011190-9411ad6e-e680-4fc4-a528-99e6380f2cc8.png)

> 等待2-3秒后，脚本的样式才生效

![image](https://user-images.githubusercontent.com/64892985/187011203-9268850c-6ab3-4b56-9524-2828e439d873.png)

浏览器版本：Google Chrome 104.0.5112.102 (正式版本)
脚本版本：26.02

个人测试：
- 同网络环境同系统下Edge浏览器下脚本是正确的，进入搜索后脚本的样式即生效
- 而在Chrome这里我尝试了重新安装脚本、降级、清除缓存都无济于事
- Google搜索中情况也是相同的

**Comment by vagitablebirdcode** [comment]
Firefox也出现了类似的问题：https://github.com/langren1353/GM_script/issues/535#issue-1347917719。
我估计解决的方法是一样的，把浏览器版本降至102或以下的，就可以恢复。

**Comment by ZiuChen** [comment]
恢复正常了，上述问题不再复现，不清楚原因
