### ISSUE TITLE
百度Lite样式,搜索输入框

### ISSUE THREAD

**Issue by superBigBlack** [langren1353/GM_script#55]
百度Lite样式,搜索输入框太短以及百度搜索历史记录过长与现有输入框长度不一致
![2019-10-25_001](https://user-images.githubusercontent.com/49225453/67540566-5d69c780-f718-11e9-8542-8c8349c8e27e.png)
![2019-10-25_002](https://user-images.githubusercontent.com/49225453/67540571-6064b800-f718-11e9-9557-a3553ebbdd27.png)

**Comment by trty** [comment]
估计是css有些问题

**Comment by langren1353** [comment]
过短的问题已经修复，过长的问题以后再说
