### ISSUE TITLE
优化谷歌精选摘要的显示逻辑

### ISSUE THREAD

**Issue by alephpi** [langren1353/GM_script#579]
您好，首先非常感谢您开发的实用工具。
我在使用谷歌双列模式时，谷歌有时会跳出多个精选摘要内容，这些内容不能很好的显示在双列栏目内。
![image](https://user-images.githubusercontent.com/61275421/205041084-05687ef1-7aad-4dd4-90d5-68d0008f7c8d.png)
如图是缩小的网页截图，其中错位的左侧是摘要，右侧是常见问题，最右侧是一个维基百科页面的翻译。这个错位问题目前我只在精选摘要推送三个及以上的摘要框遇到过。我看类似的issue已经开了不少，但是描述不够仔细，所以重开一个希望您能关注一下。

**Comment by 3biubiu** [comment]
` div[role="complementary"] {
    display: none !important;
} `  
自定义样式里添加这一条就可以去除
