### ISSUE TITLE
[Bug][Ver=26.04] Google第二页及之后的格式设置失效

### ISSUE THREAD

**Issue by fhfh32134** [langren1353/GM_script#600]
例如，Google选中单列居中，第一页正常，第二页及之后就出现错位，且每条搜索结果的标题字体、大小和第一页有区别，且无外框

**Comment by 1250456532** [comment]
我也发现了，不知道会不会修复

**Comment by alephpi** [comment]
+1，双栏模式下第一页以后的格式消失。

**Comment by langren1353** [comment]
确认下，现在应该没了

**Comment by alephpi** [comment]
> 确认下，现在应该没了

更新到26.05，感觉没啥变化。而且现在那个框也不见了。双栏的内容重叠在一起。
![image](https://github.com/langren1353/GM_script/assets/61275421/a0d7abee-ff88-4130-9964-1a677b0e3d0c)

**Comment by langren1353** [comment]
> 什么，感觉可能是浏览器的问题？我目前用

为啥你样式表掉了？
检查网址：https://ibaidu.tujidu.com/newcss/baiduCommonStyle.less?t=26.05
看这个能否打开
如果不能，那么找方法排查网络问题
如果能，建议重装脚本

**Comment by alephpi** [comment]
![image](https://github.com/langren1353/GM_script/assets/61275421/c6d861df-b759-4ffb-b14f-d6584c25dda0)
刚才以为是样式表的问题，所以清空了，现在我重置了一下还是没用。

**Comment by alephpi** [comment]
> > > 如果不能，那么找方法排查网络问题
> > > 如果能，建议重装脚本
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/61275421/246069996-c6d861df-b759-4ffb-b14f-d6584c25dda0.png) 刚才以为是样式表的问题，所以清空了，现在我重置了一下还是没用。
> 
> 检查网址能否打开 https://ibaidu.tujidu.com/newcss/baiduCommonStyle.less?t=26.05

![image](https://github.com/langren1353/GM_script/assets/61275421/3107baf1-bf45-466d-b680-458e9491265d)
打不开

**Comment by langren1353** [comment]
> [https://ibaidu.tujidu.com](https://ibaidu.tujidu.com/newcss/baiduCommonStyle.less?t=26.05)
参照这个：https://www.zhihu.com/question/342096676/answer/2433526816
看看证书现在是啥来着，神奇的东东

**Comment by alephpi** [comment]
> > [https://ibaidu.tujidu.com](https://ibaidu.tujidu.com/newcss/baiduCommonStyle.less?t=26.05)
> > 参照这个：https://www.zhihu.com/question/342096676/answer/2433526816
> > 看看证书现在是啥来着，神奇的东东

emm... edge浏览器告诉我此网站无安全证书，然后我用http手动下载了样式表装到上面，还是没用诶。
![image](https://github.com/langren1353/GM_script/assets/61275421/2c8e16ae-b414-457c-a9d6-92d46683c295)

**Comment by alephpi** [comment]
> > emm原来脚本还是回那个网站请求了一堆东西，控制台全是报错 ![image](https://user-images.githubusercontent.com/61275421/246075435-565caf2c-b1cc-47ed-89db-46305ea2526c.png)
> 
> 这已经不是某一个样式问题了，是所有的样式表都没有加载成功 所以参照这个：https://www.zhihu.com/question/342096676/answer/2433526816
> 
> 我看看证书是啥，要不你就加群，然后找我

好的我加群吧，这个回答我看了，只是教你怎么查看证书，edge就告诉我这网站没证书

**Comment by alephpi** [comment]
大佬能不能给个群号，是585532681吗？为啥这个群号我搜不到呢[苦笑]

**Comment by langren1353** [comment]
> 大佬能不能给个群号，是585532681吗？为啥这个群号我搜不到呢[苦笑]

https://github.com/langren1353/GM_script/issues/600#issuecomment-1592786847

**Comment by alephpi** [comment]
搞定。大佬把国外CDN的证书加上了，原来还是证书的问题。

**Comment by alephpi** [comment]
> ![image](https://user-images.githubusercontent.com/61275421/246106746-dc75291f-da9d-4b43-85e3-489014ca3bb3.png) 貌似还是有个小问题，第二页以后的字体明显变大了，是不是实现逻辑上不一样

该问题无法复现，issue应该可以关闭了
