### ISSUE TITLE
谷歌单列居中偶尔会出现偏移

### ISSUE THREAD

**Issue by JasonLamv-t** [langren1353/GM_script#602]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/39087996/222978032-d2c14bb2-41c2-4c38-bff8-a311148b15c1.png">

**Comment by yanghualv7** [comment]
这怎么解决啊
![Uploading 1.png…]()

**Comment by DreamL** [comment]
同样的问题,  在有首条概览结果的情况下, 一定会错位, 必现的

**Comment by Cupcc** [comment]
同样会错位！
<img width="1201" alt="image" src="https://github.com/langren1353/GM_script/assets/53716543/23c3f1e8-c0ba-4ce0-bef1-1c0b4cb0c6ef">
