### ISSUE TITLE
双列显示不全

### ISSUE THREAD

**Issue by bfqbpq567** [langren1353/GM_script#604]
langren1353大大\(^o^)/~，设置为双列，在必应，百度搜索引擎界面的双列都不会居中，要将浏览器的滑条手动往右拖一段距离才可以看见，挺麻烦，应该怎么改呢(⊙o⊙)…
![双列显示](https://user-images.githubusercontent.com/66172873/226620552-e646278f-7e90-4cbf-a723-3c79ef3ba524.png)

**Comment by bfqbpq567** [comment]
哦，这问题主要是由于火狐浏览器自带的侧边栏开启，才会导致显示不完全，关了侧边栏就不会了，不过想一直开着侧边栏，太好用了。

**Comment by alephpi** [comment]
> 哦，这问题主要是由于火狐浏览器自带的侧边栏开启，才会导致显示不完全，关了侧边栏就不会了，不过想一直开着侧边栏，太好用了。

你可以试试sidebery，可以设置成自动隐藏侧边栏。不过我用的是ArcWTF，在此基础上的一个全家桶配置，相当于模拟了一个Arc浏览器的工作区功能出来
![图片](https://github.com/langren1353/GM_script/assets/61275421/e3ae3147-40b9-4e5c-8ddb-5549cae86167)
