### ISSUE TITLE
谷歌双列显示异常

### ISSUE THREAD

**Issue by Rcrusade** [langren1353/GM_script#605]
如图

**Comment by Rcrusade** [comment]
![Snipaste_2023-03-22_23-23-38](https://user-images.githubusercontent.com/34261038/227102146-8064d61e-ac78-4c51-8d77-bcf3cb4beca8.png)

**Comment by Rcrusade** [comment]
侧边栏也关了

**Comment by cangzhouyuhe** [comment]
俺也一样

**Comment by Rcrusade** [comment]
#rso .g, .vk_c { width : 600px !important; }用这个加到自定义里去自己调

**Comment by cangzhouyuhe** [comment]
> #rso .g, .vk_c { width : 600px !important; }用这个加到自定义里去自己调

奏效了，谢谢你！

我不太懂代码，还想再向您请教两个小问题：
1.如何关闭背景图？
打开自定义样式便会开启。删去相关代码似乎无效。
2.如何才能显示右侧栏的全部？
目前使用的ChatGPT的搜索结果以右侧栏显示，双列的宽度即使调整得再小，右侧栏也不会自动向左贴近。
如蒙赐教，不胜欣喜！

**Comment by Rcrusade** [comment]
> > #rso .g, .vk_c { width : 600px !important; }用这个加到自定义正义里去自己调
> 
> 奏效了，谢谢你！
> 
> 我不太懂代码，还想再向您请教两个小问题： 1.如何关闭背景图？ 打开自定义样式便会打开。删去相关修改。 才能显示右栏的全部？ 当前使用的ChatGPT的搜索结果以右栏显示，双列的广度即使用调得再小，右栏也不会自动向左贴近。 如蒙恩教，不胜欣！

background-image就是背景图片，相关代码删了就行，要不就把opacity参数（背景图透明度）改为: 0最大1*/
  }，chatGPT的话直接下载chatgptbox插件，调好API直接浏览器有的窗口内嵌有的悬浮就没这么难看了。

**Comment by cangzhouyuhe** [comment]
谢谢你的细致回复！现在一切正常了！
&nbsp;


2392512473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月25日(星期二) 下午2:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [langren1353/GM_script] 谷歌双列显示异常 (Issue #605)





   
#rso .g, .vk_c { width : 600px !important; }用这个加到自定义正义里去自己调
  
奏效了，谢谢你！
 
我不太懂代码，还想再向您请教两个小问题： 1.如何关闭背景图？ 打开自定义样式便会打开。删去相关修改。 才能显示右栏的全部？ 当前使用的ChatGPT的搜索结果以右栏显示，双列的广度即使用调得再小，右栏也不会自动向左贴近。 如蒙恩教，不胜欣！
  
background-image就是背景图片，相关代码删了就行，要不就把opacity参数（背景图透明度）改为: 0最大1*/
 }，chatGPT的话直接下载chatgptbox插件，调好API直接浏览器有的窗口内嵌有的悬浮就没这么难看了。
