### ISSUE TITLE
请问能否支持双栏且显示侧边栏？

### ISSUE THREAD

**Issue by cangzhouyuhe** [langren1353/GM_script#619]
或者把侧边栏放入双栏中？
安装了chatgpt的侧边栏脚本，目前只能开单栏模式才能使用，求教双栏下使用的方法。
![截图_20230531130658](https://github.com/langren1353/GM_script/assets/50189901/9a87b139-fec6-4015-878f-5eb4a0a1909b)

**Comment by langren1353** [comment]
主要的原因是因为屏幕空间本来就那么大，双列放不下的
