### ISSUE TITLE
Chrome中修改百度首页的样式会导致网页崩溃

### ISSUE THREAD

**Issue by imba-tjd** [langren1353/GM_script#62]
复现步骤：

1. 使用Chrome系的浏览器。安装好脚本或者用扩展。
2. 打开F12随便修改几个样式，比如把样式的勾去掉。

![图片](https://user-images.githubusercontent.com/24759802/69787803-25aedd80-11f8-11ea-9c3f-7d1308afff53.png)

![图片](https://user-images.githubusercontent.com/24759802/69787846-38c1ad80-11f8-11ea-8b54-81b8014fb3ef.png)

**Comment by langren1353** [comment]
这个暂时无法重现

**Comment by imba-tjd** [comment]
又测试了一下，还需要登录百度账号。注销后不会崩溃。

**Comment by imba-tjd** [comment]
嗯……因为没有其他人留言，所以就关了吧
