### ISSUE TITLE
附加1-去广告功能 会屏蔽萌娘百科的部分搜索结果

### ISSUE THREAD

**Issue by CharlesChou73** [langren1353/GM_script#623]
![Snipaste_2023-06-09_14-59-01](https://github.com/langren1353/GM_script/assets/16950543/280c4469-32e2-40c0-be08-76a18cc0e3d8)
![Snipaste_2023-06-09_14-59-20](https://github.com/langren1353/GM_script/assets/16950543/5eef49a6-594e-4a45-8017-cbc9fab31e3b)
两个强关联的词条被屏蔽了，奇怪的是下面弱关联的词条还会显示

**Comment by langren1353** [comment]
有用，确实是因为百度页面发生了变更，导致拦截AD时出现误删
