### ISSUE TITLE
Mac for safari 脚本显示为JS变量,不能正常使用,希望能解决一下BUG

### ISSUE THREAD

**Issue by hibisicus** [langren1353/GM_script#624]
<img width="1066" alt="image" src="https://github.com/langren1353/GM_script/assets/46583331/4a8b215a-d8f2-4860-96f8-5cd336cdebd4">

**Comment by langren1353** [comment]
检查你的网络问题：
https://cdn.staticfile.org/vue/2.6.14/vue.min.js
https://lib.baomitu.com/vue/2.6.14/vue.min.js

至少这两个依赖其中一个能正常加载，那就能加载
