### ISSUE TITLE
26.05版本，配合谷歌扩展DarkReader后，出现颜色混乱的情况，如下图

### ISSUE THREAD

**Issue by MoConWu** [langren1353/GM_script#625]
![image](https://github.com/langren1353/GM_script/assets/33497338/90b87264-8b69-47a0-a0ae-a44245270cf8)

**Comment by MoConWu** [comment]
之前没有出现过这个情况，重置AC脚本也不行

**Comment by MoConWu** [comment]
之前没有出现过这个情况，重置AC脚本也不行

**Comment by yaomin-yang** [comment]
我的谷歌搜索加dark reader也是，暂时没找到其他办法，等待作者改进。

**Comment by alephpi** [comment]
DarkReader 有自己的一套黑化逻辑。可以在google上禁用它，尝试在自定义css中加入下列样式
```
body[google] {

  &:before {
    position: fixed;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    content: '';
  }
  
  #rso .g, .sfbg, .f6F9Be, .k8XOCe .srg, #rso, div[two-father], #rso>div:not(.g), #kp-wp-tab-overview{
    background-color: rgba(32,33,36, 1) !important; 
  }
  
  .sfbg{
    margin-top: -10px;
  }
  
  .yg51vc {
    background-color: transparent !important; 
  }
}
```

**Comment by MoConWu** [comment]
> DarkReader 有自己的一套黑化逻辑。可以在google上禁用它，尝试在自定义css中加入下列样式。（配合谷歌自带的暗色主题使用）
> ```
> body[google] {
> 
>   &:before {
>     position: fixed;
>     width: 100%;
>     height: 100%;
>     top: 0;
>     left: 0;
>     content: '';
>   }
>   
>   #rso .g, .sfbg, .f6F9Be, .k8XOCe .srg, #rso, div[two-father], #rso>div:not(.g), #kp-wp-tab-overview{
>     background-color: rgba(32,33,36, 1) !important; 
>   }
>   
>   .sfbg{
>     margin-top: -10px;
>   }
>   
>   .yg51vc {
>     background-color: transparent !important; 
>   }
> }
> ```

这是一个办法，但并不是最棒的去解决办法。而且之前都没有这个问题，大多数网站也都可以动态适应darkreader

**Comment by alephpi** [comment]
> > DarkReader 有自己的一套黑化逻辑。可以在google上禁用它，尝试在自定义css中加入下列样式。（配合谷歌自带的暗色主题使用）
> > ```
> > body[google] {
> > 
> >   &:before {
> >     position: fixed;
> >     width: 100%;
> >     height: 100%;
> >     top: 0;
> >     left: 0;
> >     content: '';
> >   }
> >   
> >   #rso .g, .sfbg, .f6F9Be, .k8XOCe .srg, #rso, div[two-father], #rso>div:not(.g), #kp-wp-tab-overview{
> >     background-color: rgba(32,33,36, 1) !important; 
> >   }
> >   
> >   .sfbg{
> >     margin-top: -10px;
> >   }
> >   
> >   .yg51vc {
> >     background-color: transparent !important; 
> >   }
> > }
> > ```
> 
> 这是一个办法，但并不是最棒的去解决办法。而且之前都没有这个问题，大多数网站也都可以动态适应darkreader

这只是个脚本，不是网站。脚本之间冲突很难让谁去迁就谁。
