### ISSUE TITLE
有点问题，搜索关键字闪一下出来结果，过一会白屏了

### ISSUE THREAD

**Issue by petercao** [langren1353/GM_script#629]
如题，
同时安装AC百度xx和searchEngineJump 搜索引擎快捷跳转
插件并打开后，
以前很长时间谷歌搜索都很OK， 但是最近不知道为啥，老是出现如题的问题，
搜索到结果，然后很快一闪白屏，反复刷新都进不去，
麻烦给看看

**Comment by langren1353** [comment]
刚安装测试了，暂时未发现问题，建议加群处理

**Comment by alfred-nice** [comment]
> 如题， 同时安装AC百度xx和searchEngineJump 搜索引擎快捷跳转 插件并打开后， 以前很长时间谷歌搜索都很OK， 但是最近不知道为啥，老是出现如题的问题， 搜索到结果，然后很快一闪白屏，反复刷新都进不去， 麻烦给看看

我也有这个问题，google搜索白屏。

**Comment by windboy12138** [comment]
这是Google搜索出来自动推荐时导致的问题，比如你搜索Google play这种简单的关键字就会触发，目前我更新了最新版脚本无此问题了。
