### ISSUE TITLE
反馈一个自主拦截域名无法隐藏的问题

### ISSUE THREAD

**Issue by Chandler-Lu** [langren1353/GM_script#63]
macOS Safari 13.0.3
tampermonkey 4.10.6103
重定向优化百度搜狗谷歌搜索脚本 23.26

---

如果没有理解错的话，两个按钮同时打开时，应该拦截生效，且按钮隐藏？但是目前好像不是这样的，不知道是不是bug，谢谢～

当“自动移除“打开，“隐藏按钮”打开时，无法拦截
![截屏2019-12-0519_44_47](https://user-images.githubusercontent.com/18322610/70233360-63cc7400-1799-11ea-96be-387d682d1dc9.png)

当“自动移除“打开，“隐藏按钮”关闭时，正常拦截
![截屏2019-12-0519_51_51](https://user-images.githubusercontent.com/18322610/70233308-40a1c480-1799-11ea-9c50-82ec7d740cfb.png)

当“自动移除“关闭，“隐藏按钮”关闭打开时，无法拦截
![截屏2019-12-0520 01 53](https://user-images.githubusercontent.com/18322610/70233725-1ac8ef80-179a-11ea-8d66-71faeeb6bc38.png)

当“自动移除“关闭，“隐藏按钮”关闭时，正常拦截
![截屏2019-12-0520 00 42](https://user-images.githubusercontent.com/18322610/70233660-f9680380-1799-11ea-94c5-5787207ca78f.png)

**Comment by langren1353** [comment]
已经修复
