### ISSUE TITLE
edge浏览器中新版本Google三列显示存在问题

### ISSUE THREAD

**Issue by HZYbest123** [langren1353/GM_script#632]
![1687715292325](https://github.com/langren1353/GM_script/assets/106685665/41570b5e-9361-4578-a903-7ade148ffa3d)
![image](https://github.com/langren1353/GM_script/assets/106685665/01170756-1fa4-47f8-8a72-14a821249813)

edge浏览器中新版本Google三列显示存在问题，文字不能完全显示，chrome中部分正常，图中从上到下分别为edge，chrome三列显示效果，and似乎版本更新后搜索结果的背景不能调成完全透明了？

**Comment by langren1353** [comment]
全透明那个是样式表的问题，其实会很影响搜索结果
