### ISSUE TITLE
AC重定向脚本与Chrome深色主题不兼容

### ISSUE THREAD

**Issue by Laign3390** [langren1353/GM_script#634]
![image](https://github.com/langren1353/GM_script/assets/67048462/1da5ed89-18cc-48c7-b127-69fa400bed4b)
26.06版本，Chrome版本 114.0.5735.199（正式版本） （64 位），默认深色主题，只有部分位置是深色

**Comment by alephpi** [comment]
Try do a little bit more search in issues before open a new one
ref https://github.com/langren1353/GM_script/issues/625 see workaround https://github.com/langren1353/GM_script/issues/625#issuecomment-1593686027
