### ISSUE TITLE
关于夜间模式的小bug

### ISSUE THREAD

**Issue by HyperKindred** [langren1353/GM_script#641]
用的edge，开启夜间模式后，像Google如果不用原始而选择单列居中，双列等自定义样式，会黑里带白，白里带黑。
![image](https://github.com/langren1353/GM_script/assets/123609087/34c27e72-58b8-4aea-a81b-8c83b7c60ba4)

**Comment by aboutmydreams** [comment]
same problem

![image](https://github.com/langren1353/GM_script/assets/34613360/db6f768c-9fa2-4e7c-bada-729776d25a0e)

**Comment by alephpi** [comment]
Try do a little bit more search in issues before open a new one
see workaround [here](https://github.com/langren1353/GM_script/issues/625#issuecomment-1593686027)
