### ISSUE TITLE
google搜索结果错位

### ISSUE THREAD

**Issue by 0614lsn** [langren1353/GM_script#646]
![image](https://github.com/langren1353/GM_script/assets/77164507/b6ad532b-dba2-4d7b-a6d3-7f44b6e0f81f)
![image](https://github.com/langren1353/GM_script/assets/77164507/17fd3ccf-f1d5-4c02-9d64-a44c5a9801d3)
单列，单列居中，双列都会这样。原始模式不会。

**Comment by Lengdrich** [comment]
我也是这个样子，不知道咋解决
