### ISSUE TITLE
请求适配多吉搜索  https://www.dogedoge.com/

### ISSUE THREAD

**Issue by Zephyr006** [langren1353/GM_script#65]
希望能适配[多吉搜索-www.dogedoge.com](https://www.dogedoge.com/)，作为新国产搜索引擎，很多时候都能找到想要的搜索结果（当然百度还是有他的优势的），原生无广告，就是**搜索结果的展示样式略显粗糙**，希望大佬能做出类似百度搜索的那种搜索结果页样式，期待+感谢！！

**Comment by langren1353** [comment]
？？？
是我适配错了吗，我好像适配了DuckDuckGo

**Comment by langren1353** [comment]
OK，现在已经适配了二狗搜索了，效果不错。
不过当前考虑到可能该搜索的性能可能不足，暂未开启对应的重定向处理

**Comment by Zephyr006** [comment]
已更新，感谢！
两个**优化建议**：
- 多吉搜索的搜索记录宽度感觉太窄，希望能比现有样式加宽_10%_左右；
- 如下图所示：有的搜索记录，图标会单独占用一行，有的搜索记录不会，希望能修复这个问题；

![image](https://user-images.githubusercontent.com/35945179/88512255-ddf78480-d018-11ea-89b9-89ca282aab17.png)


Thanks again.

**Comment by langren1353** [comment]
已适配，可能存在一定不足，基本够用
