### ISSUE TITLE
”自主拦截域名“能否添加”高级搜索模式“

### ISSUE THREAD

**Issue by Sallee1** [langren1353/GM_script#656]
在搜索一些技术类文章时，需要屏蔽百度文库和csdn，但拦截完之后，通常网页上就只剩下一两个结果甚至一个结果都没有了（全被拦截了）。

本质上，还是因为自主拦截域名，会把符合规则的搜索结果的元素直接删除（或屏蔽），下一页不在黑名单的结果不会挤到上一页。

那能不能实现这样的功能，就是给一个选项，不再拦截符合规则的搜索结果，而是通过高级搜索功能，把屏蔽网站自动附加到搜索关键词中。这样就可以使用搜索引擎的原生功能屏蔽不想要的结果，也避免了静态屏蔽导致页面空白

**Comment by langren1353** [comment]
考虑过，做出来之后的效果不佳，实现起来必要性不大，并且容易导致很多小白误操作，各种问题

感谢反馈
