### ISSUE TITLE
隐私模式恢复默认设置Bug?

### ISSUE THREAD

**Issue by Cyclonekid** [langren1353/GM_script#659]
chrome 版本 118.0.5993.88（正式版本） (arm64)   macos  14.1.1
平常喜欢用chrome的隐私模式上网

重定向脚本 设置了自己喜欢的样式和配置`    但是一旦彻底关闭  chrome  或者重启启动到隐私模式,   ac重定向的设置就被复原了.....

需求`  配置好样式后`   隐私模式重启不会还原成默认设置`

**Comment by langren1353** [comment]
无解，隐私模式就是这样的，设置会被保存在隐私的状态里面，一旦重启后，隐私的数据就自动删掉了（浏览器干的）
