### ISSUE TITLE
必应中的自定义按钮隐藏

### ISSUE THREAD

**Issue by G31415** [langren1353/GM_script#667]
1.cn.bing.com中的国内版与国外版按钮有一点重叠，看着很不舒服
2.自定义按钮能否添加隐藏功能

**Comment by alexya** [comment]
我也碰到了这个问题，“自定义”这个按钮，和Bing自身的图标都重叠了，要是能隐藏就好了，或者直接放到屏幕的左上或者右上角去。

<img width="1266" alt="image" src="https://github.com/langren1353/GM_script/assets/39186997/0abd252b-e93d-43e8-a784-e9dfd8c70ff4">
