### ISSUE TITLE
谷歌搜索结果会多一圈黑框

### ISSUE THREAD

**Issue by HatsukiH** [langren1353/GM_script#671]
![image](https://github.com/langren1353/GM_script/assets/99108047/606dd455-3b99-49aa-8771-949657b9d5cb)
前些天没有的

**Comment by gxh2517** [comment]
我自己改的，你可以是试试，替换一下
// @resource  baiduCommonStyle   https://gitee.com/gh666/Tampermonkey/raw/master/less/baiduCommonStyle.less
// @resource  baiduOnePageStyle  https://gitee.com/gh666/Tampermonkey/raw/master/less/baiduOnePageStyle.less
// @resource  baiduTwoPageStyle  https://gitee.com/gh666/Tampermonkey/raw/master/less/baiduTwoPageStyle.less
// @resource  googleCommonStyle  https://gitee.com/gh666/Tampermonkey/raw/master/less/googleCommonStyle.less
// @resource  googleOnePageStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/googleOnePageStyle.less
// @resource  googleTwoPageStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/googleTwoPageStyle.less
// @resource  bingCommonStyle    https://gitee.com/gh666/Tampermonkey/raw/master/less/bingCommonStyle.less
// @resource  bingOnePageStyle   https://gitee.com/gh666/Tampermonkey/raw/master/less/bingOnePageStyle.less
// @resource  bingTwoPageStyle   https://gitee.com/gh666/Tampermonkey/raw/master/less/bingTwoPageStyle.less
// @resource  duckCommonStyle    https://gitee.com/gh666/Tampermonkey/raw/master/less/duckCommonStyle.less
// @resource  duckOnePageStyle   https://gitee.com/gh666/Tampermonkey/raw/master/less/duckOnePageStyle.less
// @resource  duckTwoPageStyle   https://gitee.com/gh666/Tampermonkey/raw/master/less/duckTwoPageStyle.less

**Comment by HatsukiH** [comment]
> 我自己改的，你可以是试试，替换一下 // @resource baiduCommonStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/baiduCommonStyle.less // @resource baiduOnePageStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/baiduOnePageStyle.less // @resource baiduTwoPageStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/baiduTwoPageStyle.less // @resource googleCommonStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/googleCommonStyle.less // @resource googleOnePageStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/googleOnePageStyle.less // @resource googleTwoPageStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/googleTwoPageStyle.less // @resource bingCommonStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/bingCommonStyle.less // @resource bingOnePageStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/bingOnePageStyle.less // @resource bingTwoPageStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/bingTwoPageStyle.less // @resource duckCommonStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/duckCommonStyle.less // @resource duckOnePageStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/duckOnePageStyle.less // @resource duckTwoPageStyle https://gitee.com/gh666/Tampermonkey/raw/master/less/duckTwoPageStyle.less

请问怎么在插件里换上

**Comment by gxh2517** [comment]
直接在代码里面改，然后保存
