### ISSUE TITLE
双列模式概率出现遮挡

### ISSUE THREAD

**Issue by cancundeyingzi** [langren1353/GM_script#672]
![image](https://github.com/langren1353/GM_script/assets/73635883/5784db39-8e96-4bf0-a86f-296e64a87aeb)
如图,,,这啥div啊...........,有什么用
![image](https://github.com/langren1353/GM_script/assets/73635883/95abceed-3ba4-40c3-8b47-a99ae7ff1350)
删除div后的结果

**Comment by yizhucaodeyuanjing** [comment]
我最近也出现了，排查了确实是双列的问题，我用的谷歌浏览器dev最新版122，谷歌搜索。

**Comment by tup2339** [comment]
确实很奇怪，同一时间没改其它设置，试了多个搜索词，只有部分词会出现遮挡。
有的搜索词比如“basler”或“基恩士”，一定会出现遮挡，反复刷新也没用。
搜索词换成“宝视纳”或“keyence”，就怎么也不会出现遮挡。

**Comment by AkazaAkaria** [comment]
目前的我的也是存在这个问题，有解决的方式吗，还是偶现的，一会正常，一会就不行

**Comment by nishidoubi233** [comment]
我目前也是存在这个问题，反复刷新，重启电脑都没用。而且只有一些特定词会出现这种概率问题。

**Comment by linxiazhixi** [comment]
我也出现了，我几乎所有搜索第一次都全屏白，要再搜索一次才正常，只有单列正常，双列三列那些都不行

**Comment by tup2339** [comment]
在搜索词后面加个空格和*，能很大程度避免这个状况。

**Comment by FRO4TEN** [comment]
这是Google搜索出来自动推荐时导致的问题，比如你搜索Google play这种简单的关键字就会触发，目前我更新了最新版脚本无此问题了。

_Originally posted by @windboy12138 in https://github.com/langren1353/GM_script/issues/629#issuecomment-1605875539_
            
这里写到了触发原因，目前的解决方法是让关键词不那么简单，如

> 在搜索词后面加个空格和*，能很大程度避免这个状况。

**Comment by liuxiaocs7** [comment]
+1

**Comment by windboy12138** [comment]
> ```
>           这是Google搜索出来自动推荐时导致的问题，比如你搜索Google play这种简单的关键字就会触发，目前我更新了最新版脚本无此问题了。
> ```
> 
> _Originally posted by @windboy12138 in [#629 (comment)](https://github.com/langren1353/GM_script/issues/629#issuecomment-1605875539)_
> 
> 这里写到了触发原因，目前的解决方法是让关键词不那么简单，如
> 
> > 在搜索词后面加个空格和*，能很大程度避免这个状况。
> 
> P.S. 最新的脚本(26.07)仍然会出现该bug，待修复

实测 26.05、26.06 版本搜索无此bug，但是第一页搜索结果非完全居中，建议先降级至此版本使用

**Comment by klcb2010** [comment]
终于找到解决办法了
