### ISSUE TITLE
bing搜索最左侧文字会有遮挡

### ISSUE THREAD

**Issue by disappear0816** [langren1353/GM_script#675]
使用该脚本的时候会导致文字极其靠左，最左侧的部分字符（1-2个字符）会被遮挡。我以前使用的时候文字也是在最左侧但不会有遮挡，估计是bing搜索新出的这个顶部栏目导致的

相关信息edge浏览器
![image](https://github.com/langren1353/GM_script/assets/106382036/e611cf99-553d-42a7-9420-3e6ae761fe6a)

**Comment by langren1353** [comment]
已针对处理
