### ISSUE TITLE
启用后百度无法识别快递单号并列出物流轨迹

### ISSUE THREAD

**Issue by 453974158** [langren1353/GM_script#676]
启用脚本前（无痕模式）：
![QQ截图20240315234813](https://github.com/langren1353/GM_script/assets/23693576/95b9c406-ccdb-48c0-9a90-8bd3ac083fb8)
 
启用脚本后：
![QQ截图20240315234901](https://github.com/langren1353/GM_script/assets/23693576/fcaeac6a-7392-4d6c-b7b7-1bc1fc94a340)

[AC-重定向设置]以及百度搜索设置均为默认。

请问是否需要更改某处设置即可正常显示物流轨迹？

**Comment by langren1353** [comment]
原因未知，可能是什么bug导致的这块区域没被加载出来，目前测试无此问题
