### ISSUE TITLE
火狐google搜索不显示图标和链接

### ISSUE THREAD

**Issue by xiaohuirong** [langren1353/GM_script#678]
不开脚本:

![2024-03-22_14:15:56](https://github.com/langren1353/GM_script/assets/69972645/99fc271c-a2d2-49e7-bcc6-de5dee027433)

开启脚本:
![2024-03-22_14:12:12](https://github.com/langren1353/GM_script/assets/69972645/0930ef4b-c907-487e-ab83-4ab504345ec5)

**Comment by alephpi** [comment]
+1，我也不显示
火狐
![图片](https://github.com/langren1353/GM_script/assets/61275421/afa6524c-d83d-466e-ace2-818d167dd935)
Edge
![图片](https://github.com/langren1353/GM_script/assets/61275421/8ae73666-aeaf-4eff-9da1-02e4caa87967)

**Comment by alephpi** [comment]
控制台信息
关闭插件
![图片](https://github.com/langren1353/GM_script/assets/61275421/08032e99-64c3-4a09-afef-9f0b53e408cd)
开启插件
![图片](https://github.com/langren1353/GM_script/assets/61275421/90d3323d-5a09-489e-b7c0-763a7c8dfadd)

**Comment by langren1353** [comment]
个人自测，新版已经解决，如未解决，请反馈
