### ISSUE TITLE
怎么切换语言？我在海外，界面显示成英文了！我要切换成中文！

### ISSUE THREAD

**Issue by HanJjin** [langren1353/GM_script#68]
![Snipaste_2019-12-20_16-45-49](https://user-images.githubusercontent.com/44726566/71242136-3ad6e200-2348-11ea-823b-bd2ead06724e.png)

**Comment by langren1353** [comment]
更新到23.29的版本，然后有更换预压

**Comment by HanJjin** [comment]
> 更新到23.29的版本，然后有更换预压

perfect，thanks。
