### ISSUE TITLE
双列显示时搜索内容显示太少，建议统一单个搜索结果展示区域大小

### ISSUE THREAD

**Issue by star-light-breaker** [langren1353/GM_script#680]
有时候左右两列的内容高度不一致，导致整个页面大块的空白区域，建议将搜索结果固定为一定长宽。
另外bing搜索每页都有没啥卵用的相关搜索，建议屏蔽

**Comment by langren1353** [comment]
固定之后就是出滚动条，体验很差，高度不一样没关系，整体至少美观一些
