### ISSUE TITLE
求功能，把bing左边这个该死的相关搜索干掉吧

### ISSUE THREAD

**Issue by NuclearSnack** [langren1353/GM_script#682]
就是这个，每次看到都烦的不行，屁用没有一次都没点过，还自带动画吸引注意力，广告拦截也识别不了它，太烦了。求作者大佬出手解决(っ´∀｀)っ
![bing左侧搜索](https://github.com/langren1353/GM_script/assets/54259072/0b7fb13b-8ed3-4c15-8d4b-2f008ae2f211)

**Comment by langren1353** [comment]
已处理，消失
