### ISSUE TITLE
必应单列居中样式关键词人民币汇率搜索结果严重错位

### ISSUE THREAD

**Issue by 2807088219** [langren1353/GM_script#683]
例：https://cn.bing.com/search?pc=%3CCNPA01%3E&q=%E6%AC%A7%E5%85%83%E4%BA%BA%E6%B0%91%E5%B8%81%E6%B1%87%E7%8E%87
![image](https://github.com/langren1353/GM_script/assets/46000972/8620de51-b54a-4037-9814-a4eefabc266b)

**Comment by langren1353** [comment]
#633
