### ISSUE TITLE
Bing搜索在单列情况下部分按键错位严重且自己设置的背景图片不会正常显示

### ISSUE THREAD

**Issue by gugulu18** [langren1353/GM_script#687]
Bing搜索在单列情况下错位严重而且自己设置的背景图片不会正常显示，百度则正常。

**Comment by gugulu18** [comment]
![Uploading 屏幕截图 2024-06-02 165516.png…]()

**Comment by gugulu18** [comment]
背景图设置连接
https://i0.hdslb.com/bfs/new_dyn/602a9994ec3ce962f9eb0cf5a75be0e2233114659.jpg

**Comment by langren1353** [comment]
错位问题另说

图片不可见，换图床，例如：https://imgur.la/
