### ISSUE TITLE
文心智能体屏蔽

### ISSUE THREAD

**Issue by hallyoung** [langren1353/GM_script#689]
![Snipaste_2024-06-19_13-38-23](https://github.com/langren1353/GM_script/assets/69291515/2f8825bf-22ec-4812-b437-a6b5d72c1cfb)

这个智能体怎么屏蔽

我添加的规则

![Snipaste_2024-06-19_13-40-46](https://github.com/langren1353/GM_script/assets/69291515/22d0a567-2d33-48f9-8403-784a7398c68d)

**Comment by langren1353** [comment]
这个属于正常搜索结果，暂时不考虑拦截，操作也比较麻烦
