### ISSUE TITLE
百度出现只能触发一次脚本的情况

### ISSUE THREAD

**Issue by YCZ01111** [langren1353/GM_script#691]
我用edge，qq浏览器，safari访问百度，均按顺序出现以下情况：
1、第一次访问百度，脚本正常运行。
2、之后若通过搜索框搜索，则样式消失，“自定义”按钮变为默认样式且无法点击
3、点击刷新后样式恢复，脚本恢复正常运行
4、再次通过搜索框搜索，样式再次消失，但“”自定义“按钮可点击打开，且里面的选项和按键都可以使用，只是依旧没有样式（自定义中的内容会显示在网页最下方）
5、如果在第3步之后点击”自定义“中的保存，则只要浏览器不关闭，就不会再出现上述情况。若重启浏览器，依旧会出现上述情况。

**Comment by YCZ01111** [comment]
![image](https://github.com/user-attachments/assets/5636b982-1f8d-4dea-a7ed-56a1f6a96cd8)
![image](https://github.com/user-attachments/assets/5dbbab2f-ba47-48e8-99c3-dbcaaf6e3fd3)
![image](https://github.com/user-attachments/assets/e0ba768e-6968-44c9-ac3f-d43bf0d62f7e)

**Comment by YCZ01111** [comment]
![image](https://github.com/user-attachments/assets/88ecf3cd-346e-4e2c-83a2-bd65bc9824c4)
![image](https://github.com/user-attachments/assets/23db2724-c939-4632-95a1-440635f6c1ef)
![image](https://github.com/user-attachments/assets/1310116d-c133-4830-8f7d-9fb2f9b9783b)

**Comment by langren1353** [comment]
#696 一样的问题

**Comment by YCZ01111** [comment]
> #696 一样的问题

那个问题也是我~已经知道了
