### ISSUE TITLE
bing 浏览器自动翻页无效了 

### ISSUE THREAD

**Issue by 2661348402** [langren1353/GM_script#693]
![image](https://github.com/user-attachments/assets/705c0a1d-2e13-4b33-a608-3ffc78243a4e)
无法自动翻页

**Comment by iiHarry** [comment]
+1

**Comment by 2661348402** [comment]
问题已经解决了,找到了一个新的翻页脚本,可以和这个配合使用
https://github.com/XIU2/UserScript
