### ISSUE TITLE
27.02版本更新后，设置任何东西都无法保存，刷新后既失效

### ISSUE THREAD

**Issue by lobster1024** [langren1353/GM_script#707]
chrome浏览器，插件只能按照默认设置使用，任何调整刷新后都失效，重启浏览器也一样不能正常使用设置

**Comment by yogggithub** [comment]
更改设置后，需要在右上角处点击“保存XX”。很蠢的设计

**Comment by langren1353** [comment]
> 更改设置后，需要在右上角处点击“保存XX”。很智熄的设计

建议删除

**Comment by samlee111** [comment]
> 更改设置后，需要在右上角处点击“保存XX”。很智熄的设计

感谢解决了，我以为是自动保存跳了个提示，结果居然是跳了个手动保存按钮？！

**Comment by langren1353** [comment]
哈哈哈，正常正常，主要还是要用户确认一下才行，直接强行改了不大合适
