### ISSUE TITLE
每次更新后又得需要重新配置一次。

### ISSUE THREAD

**Issue by charley008** [langren1353/GM_script#712]
有没有什么办法把配置同步一下？多台电脑，或者不同浏览器（edge）的配置每次更新脚本就又得来一遍。就像今天搜索一下发现怎么页面又变了，才发现今天更新过。所有的设置又得重新来一遍。包括重定向，拦截域名，搜索设置等等。。。。

**Comment by langren1353** [comment]
可以试试这样
方案一：用TamperMonkey的高级设置项，然后去脚本的存储那里，拷贝数据到另一台上
方案二：用TamperMonkey的备份功能

脚本本身并不合适去做这汇总配置的同步的，所以没什么好的办法
