### ISSUE TITLE
搜索引擎聚合

### ISSUE THREAD

**Issue by fufumo** [langren1353/GM_script#716]
能否将搜索引擎聚合功能做一下，我发现很多类似的插件大多为搜索引擎切换
我想的是把所有的结果聚合到一个网页内
后面编注搜索引擎

**Comment by langren1353** [comment]
想过，试过
搞不定，主要是百度还是谷歌来着，不支持iframe的嵌入方法，所以就不再考虑了

**Comment by fufumo** [comment]
那就先不弄那个 别提了现在那些搜索聚合可难用了，我阅读还得来回切
