### ISSUE TITLE
希望把百度的智能回答能有开关

### ISSUE THREAD

**Issue by JohnSteve120** [langren1353/GM_script#718]
每次搜索后都会蹦出来智能回答，还要生成半天，占了很大篇幅很影响使用，希望可以自主进行开关，求！

**Comment by langren1353** [comment]
着玩意儿我搞了个双列的时候给他固定死高度的，所以双列还行，但是可能其他模式下不大好
我搞一个开关吧

**Comment by langren1353** [comment]
搜了下，我感觉还行，想了想，暂时不加这个好了，因为确实智能回答的并不多，百度也知道了很多人并不喜欢这个功能，也在逐渐的削弱这部分功能
