### ISSUE TITLE
多列模式失效

### ISSUE THREAD

**Issue by yujunhui** [langren1353/GM_script#72]
应该是 CSS 没有正确加载的问题。

`
// @resource        baiduCommonStyle     http://ibaidu.htt5.com/newcss/baiduCommonStyle.css?t=23.276
// @resource        baiduOnePageStyle    http://ibaidu.htt5.com/newcss/baiduOnePageStyle.css?t=23.276
// @resource        baiduTwoPageStyle    http://ibaidu.htt5.com/newcss/baiduTwoPageStyle.css?t=23.276
// @resource        baiduLiteStyle       http://ibaidu.htt5.com/newcss/baiduLiteStyle.css?t=23.276
// @resource        googleCommonStyle    http://ibaidu.htt5.com/newcss/googleCommonStyle.css?t=23.276
// @resource        googleOnePageStyle   http://ibaidu.htt5.com/newcss/googleOnePageStyle.css?t=23.276
// @resource        googleTwoPageStyle   http://ibaidu.htt5.com/newcss/googleTwoPageStyle.css?t=23.276
// @resource        bingCommonStyle      http://ibaidu.htt5.com/newcss/bingCommonStyle.css?t=23.276
// @resource        bingOnePageStyle     http://ibaidu.htt5.com/newcss/bingOnePageStyle.css?t=23.276
// @resource        bingTwoPageStyle     http://ibaidu.htt5.com/newcss/bingTwoPageStyle.css?t=23.276
// @resource        sogouCommonStyle     http://ibaidu.htt5.com/newcss/sogouCommonStyle.css?t=23.276
// @resource        sogouOnePageStyle    http://ibaidu.htt5.com/newcss/sogouOnePageStyle.css?t=23.276
// @resource        sogouTwoPageStyle    http://ibaidu.htt5.com/newcss/sogouTwoPageStyle.css?t=23.276
// @resource        MainHuYanStyle       http://ibaidu.htt5.com/newcss/HuYanStyle.css?t=23.276
`

在油猴上面看到这段注释，访问了一下bingTwoPageStyle，发现被亚信 block，而后我将 [bingTwoPageStyle](https://raw.githubusercontent.com/langren1353/GM_script/master/newcss/bingTwoPageStyle.css) 放到自定义样式中，页面就可以被分成两列了。

**Comment by langren1353** [comment]
这个我也没办法帮到你~亚信block了。。。
这个应该是局域网的东西吧

**Comment by yujunhui** [comment]
@langren1353 明白了，那想问下，css 是否有缓存呢？
