### ISSUE TITLE
Google搜索文字显示重叠

### ISSUE THREAD

**Issue by momoblydblk** [langren1353/GM_script#78]
![image](https://user-images.githubusercontent.com/21081757/74492667-a13a3580-4e9d-11ea-9f65-b24366506ed4.png)

Firefox 73.0 （64bit）
Windows 10

**Comment by dream-fall** [comment]
Firefox 73.0 （64bit）
Windows 10
同样的问题

**Comment by cjy825** [comment]
版本 80.0.3987.100（正式版本） （64 位）
macOS 10.15
同样问题

**Comment by matrix1001** [comment]
![image](https://user-images.githubusercontent.com/32097922/74623252-dc2eb880-517e-11ea-995c-5b6d067b7c3e.png)

我也是这个问题

![image](https://user-images.githubusercontent.com/32097922/74623244-cf11c980-517e-11ea-819c-0c0becd1905d.png)

查看元素，可能是换行什么的问题

**Comment by lafant** [comment]
同样问题，改成谷歌-原始模式之后就没有重叠了

**Comment by XmJwit** [comment]
Chrome 80.0.3987.116 （64bit）
Windows 10
同样的问题

**Comment by langren1353** [comment]
@momoblydblk @dream-fall @cjy825 @matrix1001 @lafant 
最近应该没有人提这个bug了吧，目前已经修复
