### ISSUE TITLE
动画效果能不能关掉？

### ISSUE THREAD

**Issue by StrangeMP** [langren1353/GM_script#81]
搜索时的动画效果能不能关掉？
很影响效率
个人觉得搜索结果直出就好了不需要用动画来过渡

**Comment by langren1353** [comment]
目前考虑到页面加载的时候数据显示存在闪烁的情况，于是特意加上的动画，减少页面闪烁的撕裂感。特别是在CPU和GPU并不强劲的笔记本上有明显的效果，希望理解
