### ISSUE TITLE
百度搜索栏样式错乱

### ISSUE THREAD

**Issue by nimbusking** [langren1353/GM_script#82]
是我个人问题？还是百度原生样式调整了？
![AutoCapture_2020-03-17_001902](https://user-images.githubusercontent.com/34676748/76778602-14a8cd00-67e5-11ea-8cdc-d1e30ca96d0c.jpg)

**Comment by langren1353** [comment]
在的话，直接联系我Q 1353464539

**Comment by nimbusking** [comment]
有更新？，现在看已经OK了
