### ISSUE TITLE
Google 三列出问题

### ISSUE THREAD

**Issue by BenjaminGao** [langren1353/GM_script#85]
系统：Windows10 1909
Chrome：80.0.3987.149 (正式版本) （64 位） (cohort: Stable)
脚本：油猴插件
关键字搜索：python 处理docx
脚本设置：Google 三列
问题：标题和 URL 混一起了。
![snipaste20200328_090534](https://user-images.githubusercontent.com/16028320/77811215-ea53eb00-70d3-11ea-9c4e-4c31491c6464.png)
![snipaste20200328_090917](https://user-images.githubusercontent.com/16028320/77811216-ecb64500-70d3-11ea-9aec-82c197a0c6ab.png)

**Comment by lyuinc** [comment]
遇到一样的问题，3列或者是4列的时候显示不完整，但是边上还有大量的空间可以使用。
