### ISSUE TITLE
是否可以隐藏链接后的block按钮，或者做个开关控制？

### ISSUE THREAD

**Issue by c17abab** [langren1353/GM_script#9]
和自定义按钮一样，感觉有点不太协调

**Comment by langren1353** [comment]
自定义按钮还是留着吧，下个版本我试着隐藏那个block按钮，主要是因为我不知道隐藏的选项加在哪里好看

**Comment by yueyingsk** [comment]
> 自定义按钮还是留着吧，下个版本我试着隐藏那个block按钮，主要是因为我不知道隐藏的选项加在哪里好看

在搜索结果每个链接的卡片的右上角放个眼睛的图标怎么样，点击显示操作菜单，再次确认下

**Comment by c17abab** [comment]
> 自定义按钮还是留着吧，下个版本我试着隐藏那个block按钮，主要是因为我不知道隐藏的选项加在哪里好看

个人感觉在【脚本设置】选项里添加一个开关【附加x-显示拦截图标】会不会好些

**Comment by miaomiaosoft** [comment]
![QQ截图20190426230908](https://user-images.githubusercontent.com/4084875/56817582-73d1bc00-6878-11e9-8959-e6174ed76df0.jpg)

可以实现的话移到百度快照后面应该不错，同时也换成中文 “屏蔽网站”
