### ISSUE TITLE
希望增加置顶功能

### ISSUE THREAD

**Issue by CberYellowstone** [langren1353/GM_script#98]
在搜索时若结果中有预设域名结果，则将其提升至顶部置顶
希望能实现这个功能@langren1353 @Pinming

**Comment by langren1353** [comment]
并不考虑这个功能，没太大作用

**Comment by CberYellowstone** [comment]
> 
> 
> 并不考虑这个功能，没太大作用

百度的竞价排名会导致一些真正需要结果被挤在后面
因此带来了很大的不便
我认为此功能有一定意义

**Comment by langren1353** [comment]
有意义，但是于我有风险，我不愿意承担该风险，且对于广大受众来说并不需要一个未被初始化的列表，对我来说我不愿意去做这样一个列表

**Comment by CberYellowstone** [comment]
> 有意义，但是于我有风险，我不愿意承担该风险，且对于广大受众来说并不需要一个未被初始化的列表，对我来说我不愿意去做这样一个列表

确实有风险 ,我自己魔改一下代码实现吧
