### ISSUE TITLE
【反馈】搜狗搜索提示”系统检测到您使用了有风险的插件“

### ISSUE THREAD

**Issue by sunjx17** [langren1353/GM_script#99]
![0](https://user-images.githubusercontent.com/32814176/80215283-c7830b00-866e-11ea-9dfb-73a759a9cb75.JPG)
F12源代码可见

应该是被针对了……而且搜狗搜索最近开始频繁出现需要验证才能搜索的情况。

**Comment by langren1353** [comment]
别问，问就是律师函，我害怕
已经移除了对搜狗的重定向和去广告功能。
只有双列样式效果生效
